nats-io/nats.java

README.md
I created a project to use jnats as a dependency and observed this error when attempting to build:
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact io.nats:jnats:jar:0.4-SNAPSHOT in sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots)
Upon digging into the issue, I discovered that it was a simple typo in the version that was published to the README.md file. After changing the version 0.4-SNAPSHOT to 0.4.0-SNAPSHOT, my project build completed successfully.
=> Fixed incorrect version for SNAPSHOT

pom.xml
I did some cleanup on the POM file to define properties for all dependency versions (including plugins) up near the head of the file. This will make changing versions for any dependency easier in the future.
=> Polishing up the POM file

pom.xml
Dear JNATS community,
here's some diff to provide OSGI compliant jnats bundle. Currently with the provided configuration - ie: nothing - the following manifest is generated : 
```
Manifest-Version: 1.0
Bnd-LastModified: 1462300236144
Build-Jdk: 1.8.0_72-internal
Built-By: mffrench
Bundle-Description: Java client library for NATS Messaging System
Bundle-DocURL: http://nats.io
Bundle-License: http://www.opensource.org/licenses/mit-license.php
Bundle-ManifestVersion: 2
Bundle-Name: jnats
Bundle-SymbolicName: io.nats.jnats
Bundle-Vendor: Apcera, Inc.
Bundle-Version: 0.5.0.SNAPSHOT
Created-By: Apache Maven Bundle Plugin
Export-Package: io.nats.client;uses:="javax.net.ssl";version="0.5.0.SNAP
SHOT"
Import-Package: javax.net,javax.net.ssl,org.slf4j;version="[1.7,2)"
Tool: …
```
=> add maven bundle plugin to provide OSGI compliant jnats bundle

src/main/java/io/nats/client/AsyncSubscriptionImpl.java
Currently, AsyncSubscriptionImpl leaks the msgfeeder thread on
unsubscribe because Channel.get() is never unblocked. This
overrides unsubscribe so that the thread properly terminates.
I believe this resolves issue #26.
FYI @stevenosborne-wf
=> Override unsubscribe in AsyncSubscriptionImpl

.travis.yml
Gets rid of 'git stash' errors that cause deployment to fail.
=> Added skip_cleanup to .travis.yml deploy section

pom.xml, src/main/java/io/nats/client/ServerInfo.java, src/test/java/io/nats/client/ServerInfoTest.java
gnatsd 0.9.2 and above contain an extra field (connect_urls) in the INFO message. The extra field will break jnats 0.5.0 and below. This PR causes jnats to ignore the extra field. 
Fixes #42
=> Add code to ignore connect_urls, with test. Snapshot ver set to 0.5.1

src/main/java/io/nats/client/AsyncSubscriptionImpl.java, src/main/java/io/nats/client/ConnectionImpl.java, src/test/java/io/nats/client/AsyncSubscriptionImplTest.java
Ensures that the msgFeeder thread is terminated for async subscriptions.
Resolves #26
=> Connection::close() now calls Subscription::close()

src/main/java/io/nats/client/ConnectionImpl.java
when used from clojure a package-protected `ConnectionImpl` triggers this bug -
http://dev.clojure.org/jira/browse/CLJ-1243
which is perhaps a symptom of this underlying issue with reflection -
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4283544
the effect is that trying to call `ConnectionImpl` methods overridden from `AbstractConnection`, such as `subscribeAsync`, throws an exception
```
IllegalArgumentException Can't call public method of non-public class: public io.nats.client.AsyncSubscription io.nats.client.ConnectionImpl.subscribeAsync(java.lang.String)  clojure.lang.Reflector.invokeMatchingMethod (Reflector.java:88)
```
so this PR makes the `ConnectionImpl` class public, which solves the issue, and i can't see a downside
=> make ConnectionImpl public

src/main/java/io/nats/client/ConnectionImpl.java, src/test/java/io/nats/client/ConnectionImplTest.java
All executors are shutdown in close() now.
=> Ensure all thread executors are shutdown in close()

pom.xml
Local builds were failing because parent pom 1.12 does not exist in Sonatype.  Updating to 1.13 resolves this issue.
=> Build issue - parent pom 1.12 does not exist 

src/main/java/io/nats/client/ConnectionImpl.java
Resets the `flushTimerUnit` to `MILLISECONDS` and `flushTimerInterval` to `1` for best throughput/#flush tradeoff.
=> Fix flush timing

.travis/deploy.sh
Snapshot deployment will be disabled until credential issues with maven are resolved.
=> Disable snapshot deployment

src/main/java/io/nats/client/SubscriptionImpl.java
- sets the subscription `closed` instance var
- signals any waiting poll Threads
fix for https://github.com/nats-io/java-nats/issues/111
=> clean up any poll Threads on subscription close

README.md
Parameter name reply was IMO nonoptimal since that parameter contains the request message.
=> Clarify the reply example in README.md a bit

pom.xml, src/test/java/io/nats/client/NatsServer.java
Removes the download and unpack of the NATS server from the build process and accounts for windows in testing.
* Fixes building/testing on windows
* Simplifies cross platform testing
* Allows testing with different versions of the server
Resolves #123
=> Cross platform build fixes

src/main/java/io/nats/benchmark/Benchmark.java, src/test/java/io/nats/examples/NatsBench.java
The tool is now inline with the other NATS clients bench tools.
The number of messages given in the command line is the total
number of messages to be sent. So if there is more than one publisher,
the per-publisher number is the number of messages divided
by the number of publishers (`-np`). The last publisher may get a
slight different number of messages to send due to the possible
fraction.
Each subscription is supposed to receive each message (pub/sub),
therefore each subscription receives the total number of messages
as given in the command line (`-n`).
Resolves #133
=> [FIXED] NatsBench

src/main/java/io/nats/client/ConnectionEvent.java
Removed the final modifier on ConnectionEvent and made the constructor public so it can be used in tests.
=> Allow use of ConnectionEvent in tests

src/main/java/io/nats/client/Parser.java, src/test/java/io/nats/client/ParserTest.java
The issue was when a MSG argument was constructed in several
reads from the socket. An incorrect `if` conditional was causing
the argument buffer to be reset, resulting in possible storage
of only the end of the subject.
Resolves #141
=> [FIXED] Subject truncated in message

src/main/java/io/nats/client/Message.java, src/test/java/io/nats/client/MessageTest.java
Adding null check to `io.nats.client.Message#getSubject` to match behavior with `getReplyTo` and make `toString` work, fixing #146
=> [FIXED] NPE in io.nats.client.Message#getSubject

src/main/java/io/nats/client/impl/SocketDataPort.java
Observed some performance degradation moving from jnats 1 to jnats 2, restoring the tcp socket options from jnats 1 appeard to fix this. (https://github.com/nats-io/java-nats/blob/71f4154ef7a3037356f79a3f63fc20602b505c45/src/main/java/io/nats/client/TcpConnection.java#L69-L73)
@sasbury
=> add buffer sizes to tcp socket

src/main/java/io/nats/client/impl/NatsConnection.java
We've noticed a small percentage of clients using jnats 2.4.3 (roughly 1-2%) were not able to reconnect when nats server restarted - they either seemed to hang or were stuck in a bad loop where a `Socket closed` exception kept being thrown every two seconds followed by a disconnected message.
After looking into the issue we found the clients that seemed to hang were stuck at https://github.com/yuanmwang-wf/java-nats/blob/95a229a38eab802491593808f98501053deb05aa/src/main/java/io/nats/client/impl/NatsConnection.java#L1061, which blocks the reconnect thread. I've added an executor service which enforces the connection timeout for `readInitialInfo, checkVersionRequirements and upgradeToSecureIfNeeded`, if these operations could not finish before connection timeout, an exception is thrown …
=> Fix issues with reconnection 

CHANGELOG.md, README.md, build.gradle, src/examples/java/io/nats/examples/RawTCPLatencyTest.java, src/examples/java/io/nats/examples/autobench/ThrottledBenchmark.java, src/examples/java/io/nats/examples/benchmark/NatsBench.java, src/main/java/io/nats/client/Nats.java, src/main/java/io/nats/client/Options.java, src/main/java/io/nats/client/impl/MessageQueue.java, src/main/java/io/nats/client/impl/NatsConnectionWriter.java, src/test/java/io/nats/client/SubscriberTests.java, src/test/java/io/nats/client/impl/DrainTests.java
message queue was using a lot of custom code to handle all the performance and locking requirements. Now it uses a LinkedBlockingQueue which is much simpler. The new implementation uses a poison pill to shutdown.
By switching to a blocking queue we get back pressure on publishers. This changes the performance characteristics from Autobench but mostly to smooth them out over all message sizes. Latency and request/reply performance are nominal.
Added error handler to NatsBench.
Fixed a minor warning in raw tcp test
Prepare for 2.5.0, updated all versions
=> Refactored MessagesQueue to use LinkedBlockingQueue

README.md, src/main/java/io/nats/client/Dispatcher.java, src/main/java/io/nats/client/impl/NatsDispatcher.java, src/test/java/io/nats/client/impl/DispatcherTests.java, src/test/java/io/nats/client/impl/DrainTests.java
This is a solution that satisfies what I was looking to get out of https://github.com/nats-io/nats.java/issues/197.
This adds a few new methods to the Dispatcher interface:
```java
public Subscription subscribe(String subject, MessageHandler handler);
public Subscription subscribe(String subject, String queue, MessageHandler handler);
public Dispatcher unsubscribe(Subscription subscription);
public Dispatcher unsubscribe(Subscription subscription, int after);
```
Calling `Dispatcher#subscribe` with a message handler does not treat duplicate subscriptions as a no-op. It will instead allow duplicate subscriptions to be created and managed by the caller. With this support, the Dispatcher can be used in a similar manner to v1 of this library. Behavior does not change for existing Dispatcher …
=> Add support for subscriptions with their own message handlers for Dispatcher

src/main/java/io/nats/client/Nats.java, src/main/java/io/nats/client/impl/FileAuthHandler.java, src/test/java/io/nats/client/impl/FileAuthHandlerTests.java
If one only wants to provide an NKey file but no JWT, Nats.credentials() would not be suitable because the getJWT() would throw an exception if no JWT file was specified.
Resolves #282
Signed-off-by: Ivan Kozlovic <ivan@synadia.com>
=> [FIXED] Make jwtFile optional in Nats.credentials(String jwtFile, nkeyFile)

src/main/java/io/nats/client/ErrorListener.java, src/main/java/io/nats/client/Options.java, src/main/java/io/nats/client/impl/MessageQueue.java, src/main/java/io/nats/client/impl/NatsConnection.java, src/main/java/io/nats/client/impl/NatsConnectionWriter.java, src/test/java/io/nats/client/OptionsTests.java, src/test/java/io/nats/client/TestHandler.java, src/test/java/io/nats/client/impl/ErrorListenerTests.java, src/test/java/io/nats/client/impl/MessageQueueTests.java
Fast producers may fully fill the outgoing message queue. Once this
happens, a producer will block until there is space for new messages.
This change adds the option to set the maximum number of messages in the
outgoing queue. This option can be set with property
`io.nats.client.outgoingqueue.maxmessages`, default `5000`.
Moreover, this change adds the option to discard
messages when the outgoing queue is full. This option can be set with
property `io.nats.client.outgoingqueue.discardwhenfull`, default `false`.
Clients can be notified of such event by implementing the
`messageDiscarded` callback in the `ErrorListener` interface.
Example usage:
```java
ErrorListener handler = new ErrorListener() {
public void messageDiscarded(Connection conn, Message msg) {
...
}
}
Options options = new …
```
=> Discard messages when outgoing queue is full

src/main/java/io/nats/client/impl/NatsConnectionWriter.java
`NatsConnectionWriter#canQueue` is not in line with docs.
I want to disable the reconnect buffer (used during a reconnect/disconnect) via `Options.Builder().reconnectBufferSize(0)`. According to the docs https://github.com/nats-io/nats.java/blob/master/src/main/java/io/nats/client/Options.java#L1004:
```
A value of zero will disable the reconnect buffer, a value less than zero means unlimited.
```
The reason for disabling it is that if NATS is down, the client will buffer up to 8MB by default and if the client goes down, the buffer with all the messages will vanish.
Now in `NatsConnectionWriter#canQueue`, a zero is treated like a negative number (infinite buffer):
```
boolean canQueue(NatsMessage msg, long maxSize) {
return (maxSize <= 0 || (outgoing.sizeInBytes() + msg.getSizeInBytes()) …
```
=> Allow to disable reconnectBuffer via zero size

src/main/java/io/nats/client/impl/NatsConnection.java, src/test/java/io/nats/client/impl/ReconnectTests.java
With the randomization algorithm there's a chance the client will immediately try the server it just lost connection with.  Move the last connected server to the end of the list when reconnecting.
=> Avoid retrying the last server on reconnect.

README.md, src/main/java/io/nats/client/Nats.java, src/test/java/io/nats/client/AuthTests.java
Overloads the `Nats.connect` method by adding `AuthHandler` as an argument.
Addresses https://github.com/nats-io/nats.java/issues/321
=> Nats.connect v2 credentials

build.gradle, src/main/java/io/nats/client/impl/NatsConnection.java, src/main/java/io/nats/client/impl/NatsDispatcher.java
Fixes: https://github.com/nats-io/nats.java/issues/326
Allow for JetStream subject remapping by tracking outstanding requests based on the SID (only works for "old style").
The `build.gradle` fix was useful when using Visual Studio Code which failed due to invalid `dependsOn` when `useSigning=false`.
=> Subject Remapping Fix

src/main/java/io/nats/client/impl/NatsConnection.java, src/test/java/io/nats/client/impl/DrainTests.java
Fixeds #324
Signed-off-by: Matthias Hanel <mh@synadia.com>
=> [Fixed] close connection when flush fails during drain.

src/main/java/io/nats/client/impl/NatsConnection.java, src/test/java/io/nats/client/ConnectTests.java, src/test/java/io/nats/client/impl/ReconnectTests.java
The reconnect wait option was not being honored.  Adjust the reconnect logic to honor it.
Partially resolves #329.
Resolves #290.
=> [FIX] Reconnect wait was not being honored

src/main/java/io/nats/client/impl/NatsMessage.java
=> Refactor NatsMessage to use ByteBuffer internally.

.travis.yml
Seems I botched the syntax in #346 when making `before_install` conditional on `"${TRAVIS_SECURE_ENV_VARS}" == "true"` so that pull requests from repos without the secure env vars stopped failing, this should hopefully be correct, this doesn't get run on forks or pull requests so it's a bit tricky for me to fully test.
=> Fix before_install formatting.

src/test/java/io/nats/client/ConnectTests.java, src/test/java/io/nats/client/impl/ConnectionListenerTests.java, src/test/java/io/nats/client/impl/ReconnectTests.java, src/test/java/io/nats/client/impl/TLSConnectTests.java, src/test/java/io/nats/client/impl/TestMacros.java
These test are flappers, failing because of timeout. But they are not testing timing, they are testing state, so timeout should not matter.
While I was in these files... nit fixed to use assertSame when testing connection status / enums
=> fix test failing because of timeout that aren't testing timing

src/main/java/io/nats/client/Connection.java, src/main/java/io/nats/client/impl/DataPort.java, src/main/java/io/nats/client/impl/NatsConnection.java, src/main/java/io/nats/client/impl/NatsConnectionWriter.java, src/main/java/io/nats/client/impl/SocketDataPort.java, src/test/java/io/nats/client/ConnectTests.java
This PR adds a flush buffer API to flush the underlying socket (through the socket output stream).
I did use a synchronized API on the connection writer because research seemed to indicate the best performance with a smaller number of threads - at least in older versions of java.  It also fit well with the current architecture since there is no connection level locking.  Instead publish synchronization resolves around the message writer and message queue.  There's a small chance when publishing and immediately doing a flushBuffer, the flushBuffer will beat the message writer, but without major surgery I'm not sure how to fix that.
Regardless, I was able to exceed capacity of the underlying message queue unless I flushed in the test itself so performance doesn't seem to be impacted much. …
=> Add a flushBuffer API

README.md, build.gradle, src/main/java/io/nats/client/NKey.java, src/main/java/io/nats/client/NUID.java, src/test/java/io/nats/client/NKeyTests.java
The bug causing `/dev/random` to be used on Linux is due to the `SHA1PRNG`(use of which is generally discouraged) instance of `SecureRandom` being used, use the OS default instance to fix this issue which should properly select `/dev/urandom` on Linux and have sane defaults on other systems.
=> Use OS Default SecureRandom.

build.gradle
=> Automatic-Module-Name clause added to jar manifest.

src/main/java/io/nats/client/impl/NatsJetStream.java, src/main/java/io/nats/client/impl/NatsMessage.java, src/main/java/io/nats/client/support/Validator.java, src/test/java/io/nats/client/support/ValidatorTests.java
NatsMesasage: 
. . . . subject is required, but no other checks
NatsJetStream.addConsumer:
. . . . subject: No subject check, it's not required
. . . . stream:, required, alphanum or dash `^[a-zA-Z0-9-]+$`
NatsJetStream.subscribe:
. . . . subject: not required but if provided cannot contain whitepsace
. . . . queue: required and cannot contain whitespace
=> get the validation right

src/examples/java/io/nats/examples/stability/JsMulti.java, src/main/java/io/nats/client/JetStreamOptions.java, src/main/java/io/nats/client/api/StreamConfiguration.java, src/main/java/io/nats/client/impl/NatsConnection.java, src/main/java/io/nats/client/impl/NatsJetStream.java, src/main/java/io/nats/client/support/JsPrefixManager.java, src/test/java/io/nats/client/impl/JetStreamManagementTests.java, src/test/java/io/nats/client/impl/JetStreamPubTests.java, src/test/java/io/nats/client/impl/JetStreamTestBase.java
handle no ack, fix bug in JsPrefixManager
=> handle no ack publishing

src/main/java/io/nats/client/Options.java, src/test/java/io/nats/client/impl/TLSConnectTests.java, src/test/java/io/nats/client/utils/TestBase.java
when there were multiple servers in the options (either comma delimited string or added by builder, or array, etc.) the ssl context was not created if it was not already supplied as it was set to handle only when there was exactly 1 server
=> 340 tls opentls multiple servers in url string / array

src/main/java/io/nats/client/support/ByteArrayBuilder.java
Fixes:
```
/home/runner/work/nats.java/nats.java/src/main/java/io/nats/client/support/ByteArrayBuilder.java:338: error: tag not supported in the generated HTML version: tt
*         <tt>array.length - offset</tt>
^
/home/runner/work/nats.java/nats.java/src/main/java/io/nats/client/support/ByteArrayBuilder.java:356: error: tag not supported in the generated HTML version: tt
*         must be non-negative and no larger than <tt>array.length</tt>
^
/home/runner/work/nats.java/nats.java/src/main/java/io/nats/client/support/ByteArrayBuilder.java:360: error: tag not supported in the generated HTML version: tt
*         <tt>array.length - offset</tt>
^
```
=> Fix docs build.

src/test/java/io/nats/client/impl/ReconnectTests.java
The config for a cluster needs a name. This test was somehow working, but was a flapper. Not sure why it worked sometimes without a cluster name, but should always work now.
=> cluster name required in test config

src/main/java/io/nats/client/JetStreamApiException.java, src/main/java/io/nats/client/api/ApiResponse.java, src/main/java/io/nats/client/api/Error.java, src/main/java/io/nats/client/impl/NatsJetStream.java, src/main/java/io/nats/client/support/ApiConstants.java, src/main/java/io/nats/client/support/NatsJetStreamConstants.java, src/test/java/io/nats/client/api/ApiResponseTests.java, src/test/java/io/nats/client/impl/JetStreamManagementTests.java, src/test/java/io/nats/client/impl/JetStreamTestBase.java
A unit test failed on the nightly because the server changed the text of an error. This fix is to use the new err_code field supplied in the json of api error response, instead of using the text.
=> use internal error codes

src/main/java/io/nats/client/impl/NatsJetStream.java
during subscribe, we used to set max_ack_pending if it was not supplied, but we set it to pendingMessageLimit which defaults to 64k. The server default for max_ack_pending is 20K. Seems like the right behavior to let the server set this value.
=> max_ack_pending set by server if not provided

src/main/java/io/nats/client/impl/NatsJetStream.java
Fixing this change that was not backward compatible: https://github.com/nats-io/nats.java/commit/d3e2c0e675c4843ed259212f36024574a133954d#diff-7bae7dec65886ecd48115d9367d773a51255027e6f885b882dba2f915960241b
=> bw compatibility restored on checking consumer not found

src/main/java/io/nats/client/impl/NatsSubscription.java
The next message implementation tries to retrieve a message from the internal buffer and increments the delivered count whether or not there was a message. This seems like a bug, and the PR fixes it. Need confirmation that it should only increment the delivered count when a message is actually found.
=> don't increment delivered count if no message was retrieved

src/main/java/io/nats/client/KeyValue.java, src/main/java/io/nats/client/impl/NatsJetStreamManagement.java, src/main/java/io/nats/client/impl/NatsKeyValue.java, src/main/java/io/nats/client/impl/NatsKeyValueWatchSubscription.java, src/test/java/io/nats/client/impl/KeyValueTests.java
https://github.com/nats-io/nats-architecture-and-design/issues/93
**KeyValue.java** 
* Added interface method overload which takes a revision parameter
**NatsJetStreamManagement.java** 
* Changed imports for readability
* Underlying MessageInfo object changed to be consistent, so had to manually throw on error
**NatsKeyValue.java**
* Implemented get with revision with refactor to original get to share common code.
* NatsKeyValueWatchSubscription.java
* Use minor refactor 
**KeyValueTests.java**
* test the implementation
=> kv get with revision

README.md, build.gradle, src/examples/java/io/nats/examples/README.md, src/examples/java/io/nats/examples/autobench/NatsAutoBench.java, src/main/java/io/nats/client/api/ServerInfo.java, src/main/java/io/nats/client/api/StorageType.java, src/test/java/io/nats/client/api/ServerInfoTests.java, src/test/resources/data/StreamConfiguration.json
* Changed version from 2.14.0 to 2.14.1, saves time for upcoming snapshot builds
* **ServerInfo.java** changed to match fix to .NET library
* **ServerInfoTests.java**
* **StorageType.java** simplified get method which matches to string
* **StreamConfiguration.json** test data to exercise StorageType change
All other files are a version change
=> 2.14.1 and misc

src/main/java/io/nats/client/Connection.java, src/main/java/io/nats/client/impl/NatsConnection.java, src/test/java/io/nats/client/impl/RequestTests.java
Give the possibility to clients to specify a timeout while performing async requests.
More details in [#616](https://github.com/nats-io/nats.java/issues/616)
=> Support for timeout propagation in async requests

README.md, src/main/java/io/nats/client/api/ConsumerConfiguration.java, src/main/java/io/nats/client/impl/NatsJetStream.java, src/main/java/io/nats/client/support/JsonUtils.java, src/main/java/io/nats/client/support/NatsJetStreamClientError.java, src/main/java/io/nats/client/support/Validator.java, src/test/java/io/nats/client/api/ConsumerConfigurationTests.java, src/test/java/io/nats/client/impl/ConsumerConfigurationComparerTests.java, src/test/java/io/nats/client/impl/JetStreamGeneralTests.java, src/test/java/io/nats/client/impl/JetStreamManagementTests.java, src/test/java/io/nats/client/support/JsonUtilsTests.java, src/test/java/io/nats/client/utils/TestBase.java
addressing server defaults and unsigned ints better
=> Value or default bug

README.md, src/examples/java/io/nats/examples/jetstream/NatsJsPullSubBatchSize.java, src/main/java/io/nats/client/JetStreamSubscription.java, src/main/java/io/nats/client/KeyValueOptions.java, src/main/java/io/nats/client/PullRequestOptions.java, src/main/java/io/nats/client/PurgeOptions.java, src/main/java/io/nats/client/SubscribeOptions.java, src/main/java/io/nats/client/api/ConsumerConfiguration.java, src/main/java/io/nats/client/impl/NatsJetStream.java, src/main/java/io/nats/client/impl/NatsJetStreamPullSubscription.java, src/main/java/io/nats/client/impl/NatsJetStreamSubscription.java, src/main/java/io/nats/client/impl/NatsSubscription.java, src/main/java/io/nats/client/impl/PullStatusMessageManager.java, src/main/java/io/nats/client/support/ApiConstants.java, src/main/java/io/nats/client/support/JsonUtils.java, src/main/java/io/nats/client/support/NatsJetStreamClientError.java, src/test/java/io/nats/client/SubscribeOptionsTests.java, src/test/java/io/nats/client/SubscriberTests.java, src/test/java/io/nats/client/api/ConsumerConfigurationTests.java, src/test/java/io/nats/client/api/StreamInfoTests.java, src/test/java/io/nats/client/impl/ConsumerConfigurationComparerTests.java, src/test/java/io/nats/client/impl/JetStreamGeneralTests.java, src/test/java/io/nats/client/impl/JetStreamManagementTests.java, src/test/java/io/nats/client/impl/JetStreamPullTests.java, src/test/java/io/nats/client/impl/JetStreamPushTests.java, src/test/java/io/nats/client/impl/KeyValueTests.java, src/test/java/io/nats/client/impl/MessageManagerTests.java, src/test/java/io/nats/client/impl/NatsMessageTests.java, src/test/resources/data/ConsumerConfiguration.json
* architecture issue 112 Pull config changes  in ConsumerConfig and JSApiConsumerGetNextRequest
* remove enforcement of durable on pull subscriptions allowing ephemeral pull consumers
* unit tests for above and additional unit tests to shore up coverage
=> Pull config changes, ephemeral pull, unit tests

src/main/java/io/nats/client/api/ConsumerConfiguration.java
There was incorrect documentation in the consumer config for inactive threshold builder method
=> fix inactive threshold doc

src/examples/java/io/nats/examples/jetstream/NatsJsPushSubQueueDurable.java
old version did not use the deliver group configuration, relying on the fact that the client will fix it on the initial consumer if the subscription is a queue subscription
=> better push queue example

src/test/java/io/nats/client/NKeyTests.java
Test that `key.getPrivateKey()` throws an `IllegalArgumentException` when `clear` is called. 
This tests the method [`NKey.clear`](https://github.com/nats-io/nats.java/blob/ddf96321702ff70d0b98d6e5c8d0b6b7987c312d/src/main/java/io/nats/client/NKey.java#L559). 
This test is based on the test [`testEquals`](https://github.com/nats-io/nats.java/blob/ddf96321702ff70d0b98d6e5c8d0b6b7987c312d/src/test/java/io/nats/client/NKeyTests.java#L582).
(I wrote this test as part of a research study at TU Delft. [Find out more](https://github.com/lacinoire/lacinoire/blob/main/README.md))
=> Add test for NKey.clear

src/main/java/io/nats/client/Options.java, src/main/java/io/nats/client/impl/NatsConnection.java, src/main/java/io/nats/client/support/Encoding.java, src/test/java/io/nats/client/AuthTests.java, src/test/resources/encoded_pass.conf
Wrote unit test to verify that encoded urls are accepted. This uncovered an issue with the an encoded colon `:` in the url, so this was fixed.
=> Accept encoded connection urls

src/main/java/io/nats/client/api/ConsumerInfo.java, src/main/java/io/nats/client/api/SequenceInfo.java, src/main/java/io/nats/client/api/SequencePair.java, src/main/java/io/nats/client/support/ApiConstants.java, src/test/java/io/nats/client/api/ConsumerInfoTests.java, src/test/java/io/nats/client/impl/ListRequestsTests.java, src/test/resources/data/ConsumerInfo.json, src/test/resources/data/ConsumerListResponse.json
https://github.com/nats-io/nats.java/issues/671
* A new object was created, `SequenceInfo` which extends `SequencePair`
* The `ConsumerInfo.delivered` and `ConsumerInfo.ackFloor` fields where changed to this type.
Backward compile compatibility was ensured by the subclass, meaning if you assigned `getDelivered()` to a SequencePair, this is fine, it still is a SequencePair.
=> consumer info change to sequence_info from sequence_pair

src/main/java/io/nats/client/impl/NatsConnection.java, src/main/java/io/nats/client/support/NatsRequestCompletableFuture.java
https://github.com/nats-io/nats.java/issues/687
Changed the code to use Options RequestCleanupInterval, which defaults to 5 seconds.
=> better request timeout management

README.md, src/main/java/io/nats/client/ObjectStore.java, src/main/java/io/nats/client/impl/NatsObjectStore.java, src/main/java/io/nats/client/support/NatsJetStreamClientError.java, src/test/java/io/nats/client/impl/ObjectStoreTests.java
* specific error for link not allowed in meta used for putting and object
* object store adr changes to getInfo
=> object store tuning

src/main/java/io/nats/client/impl/NatsConnectionWriter.java
I believe there is an issue related to resizing the `sendBuffer` during the `sendMessageBatch` in `NatsConnectionWriter`.
This should fix an `ArrayIndexOutOfBoundsException` that could occur when the `sendBuffer` is (not) resized during specific scenarios.
A more detailed explanation of the issue:
https://github.com/nats-io/nats.java/issues/644#issuecomment-1257709076
=> Ensure resizing of the sendBuffer

src/main/java/io/nats/client/impl/NatsMessage.java, src/test/java/io/nats/client/impl/MessageQueueTests.java, src/test/java/io/nats/client/impl/NatsMessageTests.java, src/test/java/io/nats/client/impl/SlowConsumerTests.java
The calculation of `getSizeInBytes()` was off, when looking at the usage in `NatsConnectionWriter.sendMessageBatch(...)`.
The following would happen:
| Message | Previously | Comment |
|:--|:--|:--|
| only subject | calculation off by -2 | When `accumulate` was called on the `MessageQueue` it would return more messages. `sendMessageBatch(...)` would write more bytes than was indicated by the msg size, so it would more easily trigger re-sizing of the `sendBuffer`. (Which I believe is the root cause of: https://github.com/nats-io/nats.java/issues/644)  |
| subject+headers | correct calculation | |
| subject+data | correct calculation | |
| subject+headers+data | calculation off by +2 | `MessageQueue.accumulate` would return less messages than would fit in the `sendBuffer`. Shouldn't be as …
=> Sync NatsMessage.getSizeInBytes() with usage in NatsConnectionWriter

README.md
Changed nc.Jetstream() to nc.jetStream() as the method is not with capital J.
=> Minor fix for README.md Jetstream example

src/test/java/io/nats/client/AuthTests.java
This pull request fixes a unit test that uses an insecure creation of a temporary file. It is not a library vulnerability because it is not part of the runtime library, therefore does not make the project vulnerable to local information disclosure.
The system temporary directory is shared between all users on most unix-like systems (not MacOS, or Windows). Thus, code interacting with the system temporary directory must be careful about file interactions in this directory, and must ensure that the correct file posix permissions are set.
With the default uname configuration, `File.createTempFile(..)` creates a file with the permissions `-rw-r--r--`. This means that any other user on the system can read the contents of this file.
> If this code was found in the runtime library it would be …
=> [Patch] Change Temporary File Creation in unit test.

README.md, src/main/java/io/nats/client/Consumer.java, src/main/java/io/nats/client/PullSubscribeOptions.java, src/main/java/io/nats/client/PushSubscribeOptions.java, src/main/java/io/nats/client/SubscribeOptions.java, src/main/java/io/nats/client/impl/NatsConsumer.java, src/main/java/io/nats/client/impl/NatsJetStream.java, src/main/java/io/nats/client/support/NatsJetStreamClientError.java, src/test/java/io/nats/client/impl/JetStreamPushTests.java, src/test/java/io/nats/client/impl/SlowConsumerTests.java
* from 64K to 512K to match GO.
helps reduce client side slow consumer
see https://github.com/nats-io/nats-architecture-and-design/issues/172
=> increase default max (pending) messages, ability to set pending limits in subscribe options

src/main/java/io/nats/client/api/ConsumerConfiguration.java
When setting the `inactiveThreshold(...)` the docs mentioned that this only applied to ephemeral consumers. However, since the 2.9.0 nats-server release this also applies to durables.
=> fix inactiveThreshold docs in ConsumerConfiguration

src/main/java/io/nats/client/api/KeyValueConfiguration.java, src/main/java/io/nats/client/api/ObjectStoreConfiguration.java, src/main/java/io/nats/client/api/ServerInfo.java, src/main/java/io/nats/client/api/StreamConfiguration.java, src/main/java/io/nats/client/support/Validator.java, src/test/java/io/nats/client/api/KeyValueConfigurationTests.java, src/test/java/io/nats/client/api/ObjectStoreApiTests.java, src/test/java/io/nats/client/api/ServerInfoTests.java, src/test/java/io/nats/client/api/StreamConfigurationTests.java, src/test/java/io/nats/client/support/ValidatorTests.java
Consistent validation across Stream, KeyValue and ObjectStore configuration https://github.com/nats-io/nats.java/issues/821
Version comparison fix https://github.com/nats-io/nats.java/issues/822
=> [FIX] consistent validation and version comparison fix

src/main/java/io/nats/client/Options.java
No much to explain to be honest.
=> Add Options.builder() method to get the builder in a more "fluent" manner

src/main/java/io/nats/client/JetStream.java, src/main/java/io/nats/client/impl/NatsDispatcher.java
https://github.com/nats-io/nats.java/issues/840
=> Dispatcher with no default handler sometimes has NPE during close if messages are still coming in

src/main/java/io/nats/service/Discovery.java, src/test/java/io/nats/service/ServiceTests.java
and also allow the user to provide their own supplier. Addressing #856
=> use standard connection create inbox for discovery

src/main/java/io/nats/client/Connection.java, src/main/java/io/nats/client/impl/NatsConnection.java, src/test/java/io/nats/client/impl/ConnectionListenerTests.java
This patch addresses #860.
Late and multiple bindings of ConnectionListeners to Connections enable business logic to listen for events without needing to construct their own Connection object.
This benefits applications which separate their NATS Connection factory from their business logic, but whose business logic's resource's lifecycle are coupled to the state of NATS Connection's.  Eg: They wish to clean up on connection CLOSED events without polling or passing around a separate observable mechanism.
=> Enable add/remove of multiple ConnectionListeners per Connection

src/main/java/io/nats/client/Options.java, src/test/java/io/nats/client/OptionsTests.java
=> Options Builder constructor that takes existing Options

src/examples/java/io/nats/examples/DontCancelOnNoResponders.java, src/examples/java/io/nats/examples/ReportNoResponders.java, src/main/java/io/nats/client/JetStreamStatusException.java, src/main/java/io/nats/client/Options.java, src/main/java/io/nats/client/impl/NatsConnection.java, src/main/java/io/nats/client/impl/NatsJetStream.java, src/main/java/io/nats/client/impl/NatsJetStreamImpl.java, src/main/java/io/nats/client/support/NatsRequestCompletableFuture.java, src/main/java/io/nats/client/support/Status.java, src/test/java/io/nats/client/RequestTests.java, src/test/java/io/nats/client/impl/RequestTests.java, src/test/java/io/nats/client/utils/TestBase.java
Adding a `reportNoResponders` connection option flag. Will make core no responders exception differently when core-publishing to a subject.
This should really be the default behavior, but it would be a breaking change.
```
java.util.concurrent.CancellationException
```
to this
```
java.util.concurrent.ExecutionException: io.nats.client.JetStreamStatusException: 503 No Responders Available For Request
```
=> New connection option reportNoResponders

src/main/java/io/nats/client/support/WebsocketInputStream.java
Addresses: https://github.com/nats-io/nats.java/issues/900
Might need a regression test?
=> only read payload from network stream

src/main/java/io/nats/client/support/JsonUtils.java, src/main/java/io/nats/client/support/JwtUtils.java, src/test/java/io/nats/client/support/JwtUtilsTests.java
The `JwtUtils` didn't include the `subs`, `data` and `payload`. This made the server default those limits to 0, not allowing for any subs to be created, etc.
Looking at the NATS JWT Go implementation:
```go
// NewUserClaims creates a user JWT with the specific subject/public key
func NewUserClaims(subject string) *UserClaims {
if subject == "" {
return nil
}
c := &UserClaims{}
c.Subject = subject
c.Limits = Limits{
UserLimits{CIDRList{}, nil, ""},
NatsLimits{NoLimit, NoLimit, NoLimit},
}
return c
}
```
These fields are defaulted to `NoLimit`, so -1, in the `NatsLimits` (which contains the `subs`, `data`, `payload`).
To support the Java client I've added support for overwriting these fields in the `UserClaim`, as well as defaulting them to `NO_LIMIT = -1` to ensure these are set explicitly …
=> JwtUtils: support subs, data, payload & default to no limit / -1

src/main/java/io/nats/client/api/ConsumerConfiguration.java, src/main/java/io/nats/client/impl/NatsJetStream.java, src/test/java/io/nats/client/api/ConsumerConfigurationTests.java
Building a consumer config allowed the user to supply a long for fields that where only 32 bit signed values. Even though it would be unusual for a developer to provide a value larger than 2,147,483,647 it's still possible from the builder interface.
This fix checks the value and if it's larger than 2,147,483,647 it just makes it 2,147,483,647. 
This seems reasonable as the user probably meant unlimited which this still provides.
=> [BUG] Consumer Config fields are 32 bits (ints) not 64 bits (longs)

README.md, src/main/java/io/nats/client/Options.java, src/main/java/io/nats/client/support/SSLUtils.java, src/test/java/io/nats/client/AuthTests.java, src/test/java/io/nats/client/OptionsTests.java, src/test/java/io/nats/client/TestSSLUtils.java, src/test/java/io/nats/client/impl/TLSConnectTests.java, src/test/java/io/nats/client/utils/ResourceUtils.java, src/test/resources/options_coverage_with_prefix.properties, src/test/resources/options_coverage_with_prefix_underscore.properties, src/test/resources/options_coverage_without_prefix.properties, src/test/resources/options_coverage_without_prefix_underscore.properties
* Allow creation of connections requiring an AuthHandler for JWT to specify the credentials file in a properties files, instead of needing to provide an instance of AuthHandler in code.
* Allow creation of connections requiring an SSL context to specify key and trust store information in a properties files so an SSLContext can be created automatically instead of needing to provide an instance of an SSLContext in code.
* Support properties keys with or without the prefix 'io.nats.client.'
| Property| Description|
| --- | --- |
| credential.path | Used to set the path to a credentials file to be used in a FileAuthHandler |
| keyStore | Property for the keystore path used to create an SSLContext |
| trustStore | Property for the truststore path used to create an SSLContext |
| …
=> Improving Options with better construction via properties

src/main/java/io/nats/client/NKey.java, src/main/java/io/nats/client/support/Encoding.java, src/main/java/io/nats/client/support/JsonUtils.java, src/main/java/io/nats/client/support/JwtUtils.java, src/test/java/io/nats/client/support/JwtUtilsTests.java
* JWT Utils now supports "audience" `aud`
=> Jwt Utils update to support "audience"

src/main/java/io/nats/client/Options.java, src/test/java/io/nats/client/OptionsTests.java
Developer used to have to load the properties file themselves. Now they can just supply the file path and the Options builder will do it for them.
=> Construct Options builder from properties file for user.

README.md
Make the library's version info more visible.
=> README.md library version more visible

README.md, src/main/java/io/nats/client/Options.java, src/main/java/io/nats/client/impl/NatsConnection.java, src/test/java/io/nats/client/OptionsTests.java, src/test/java/io/nats/client/PublishTests.java, src/test/resources/max_payload.conf
Revert this PR: https://github.com/nats-io/nats.java/pull/922
=> Revert removal of client side checks

src/test/java/io/nats/client/impl/JetStreamConsumerTests.java, src/test/java/io/nats/client/impl/JetStreamGeneralTests.java, src/test/java/io/nats/client/impl/JetStreamMirrorAndSourcesTests.java, src/test/java/io/nats/client/impl/JetStreamPubTests.java, src/test/java/io/nats/client/impl/JetStreamPullTests.java, src/test/java/io/nats/client/impl/JetStreamPushAsyncTests.java, src/test/java/io/nats/client/impl/JetStreamPushQueueTests.java, src/test/java/io/nats/client/impl/JetStreamPushTests.java, src/test/java/io/nats/client/impl/JetStreamTestBase.java, src/test/java/io/nats/client/impl/MessageManagerTests.java, src/test/java/io/nats/client/impl/SimplificationTests.java, src/test/java/io/nats/client/utils/TestBase.java
Removing generic-ness from naming of stream/subject/etc to allow for safely running tests in shared servers
=> [Tests] Removing generic-ness from naming

src/main/java/io/nats/client/api/PublishAck.java, src/test/java/io/nats/client/api/PublishAckTests.java
Potential fix for: https://github.com/nats-io/nats.java/issues/1002
Duplicate messages for Interest-based streams are immediately returned by the server with a `seq: 0` if there is no interest, which would error in `PublishAck`.
=> Fix: duplicate message for Interest stream fails seq check in PublishAck

src/main/java/io/nats/client/Options.java
Initialize SocketDataPort directly when dataPortType is not overridden. Better for GraalVM
=> Initialize SocketDataPort directly

src/main/java/io/nats/client/api/StreamConfiguration.java, src/test/java/io/nats/client/api/StreamConfigurationTests.java
This commit adds a public method to StreamConfiguration that allows hydrating a StreamConfiguration via a JSON String. Previously this was only package scoped and used in tests.
=> Support StreamConfiguration creation from JSON

build.gradle
jnats-server-runner 1.2.6 has better output when server fails to run during unit testing.
=> Update jnats-server-runner to 1.2.6

src/main/java/io/nats/client/Options.java, src/main/java/io/nats/client/impl/NatsConnection.java, src/main/java/io/nats/client/support/NatsRequestCompletableFuture.java, src/test/java/io/nats/client/impl/RequestTests.java
It would be nice to take the first step in this direction - #797 
Since this change is still "breaking", we can make it optional until next version
=> TimeoutException instead of CancellationException on timeout

src/main/java/io/nats/client/Connection.java, src/main/java/io/nats/client/ObjectStore.java, src/main/java/io/nats/client/ObjectStoreManagement.java, src/main/java/io/nats/client/ObjectStoreOptions.java, src/main/java/io/nats/client/api/FeatureConfiguration.java, src/main/java/io/nats/client/api/KeyValueConfiguration.java, src/main/java/io/nats/client/api/KeyValueStatus.java, src/main/java/io/nats/client/api/ObjectInfo.java, src/main/java/io/nats/client/api/ObjectLink.java, src/main/java/io/nats/client/api/ObjectMeta.java, src/main/java/io/nats/client/api/ObjectMetaOptions.java, src/main/java/io/nats/client/api/ObjectStoreConfiguration.java, src/main/java/io/nats/client/api/ObjectStoreStatus.java, src/main/java/io/nats/client/api/ServerInfo.java, src/main/java/io/nats/client/api/StreamConfiguration.java, src/main/java/io/nats/client/support/JsonValue.java, src/main/java/io/nats/client/support/JsonValueUtils.java, src/test/java/io/nats/client/api/KeyValueConfigurationTests.java, src/test/java/io/nats/client/api/ObjectStoreApiTests.java, src/test/java/io/nats/client/api/StreamConfigurationTests.java, src/test/java/io/nats/client/impl/KeyValueTests.java, src/test/java/io/nats/client/impl/ObjectStoreTests.java, src/test/java/io/nats/client/support/JsonParsingTests.java, src/test/java/io/nats/client/utils/TestBase.java
* Add compression and metadata support to KV and OS
* Some test efficiency improvements.
* JsonValue utility improvements to support toString for KV and OS objects
* Removal of EXPERIMENTAL label on Object Store
=> KV and OS Compression and Metadata

src/main/java/io/nats/client/impl/MessageManager.java, src/main/java/io/nats/client/impl/OrderedMessageManager.java
Didn't quite get ordered push recovery correct, fixed it.
=> Ordered Push don't cancel sub if trying to recover

src/main/java/io/nats/client/api/MessageInfo.java, src/main/java/io/nats/client/impl/Headers.java, src/main/java/io/nats/client/impl/NatsMessage.java, src/main/java/io/nats/client/support/NatsJetStreamConstants.java, src/test/java/io/nats/client/impl/HeadersTests.java, src/test/java/io/nats/client/impl/JetStreamManagementTests.java, src/test/java/io/nats/client/impl/NatsMessageTests.java
When a message is made, copy the headers and make them read only. Currently headers could be modified since they are just a reference to what the dev put in the message, but the length calculations are already done and changing headers will have a bad side effect.
=> Message Headers Improvement

build.gradle, src/examples/java/io/nats/examples/ExampleAuthHandler.java, src/main/java/io/nats/client/AuthHandler.java, src/main/java/io/nats/client/NKey.java, src/main/java/io/nats/client/impl/FileAuthHandler.java, src/main/java/io/nats/client/impl/StringAuthHandler.java, src/test/java/io/nats/client/NKeyTests.java
* Original `io.nats.client.NKey` class kept for full backward compatibility. Marked as deprecated.
* Internally, changed to use the `io.nats.nkey.Nkey` class
=> NKey class is deprecated.

src/main/java/io/nats/client/api/ConsumerConfiguration.java
Hi there 👋
Just stumbled upon an issue setting both ackwait and backoff in the consumer configuration. 
As per the [documentation ](https://docs.nats.io/using-nats/developer/develop_jetstream/consumers#delivery-reliability):
> You can control the timing of re-deliveries using either the single AckWait duration attribute of the consumer, or as a sequence of durations in the BackOff attribute (which overrides AckWait).
Backoff will override AckWait, I thought it would be great to specify this in the javadoc.
I think it's also worth logging an error at runtime when both are set but I'm not sure where to plug this ?
Let me know if you want me to do any change
=> chore: upgrade documentation to specify backoff behaviour

src/main/java/io/nats/client/Options.java, src/main/java/io/nats/client/impl/DispatcherFactory.java, src/main/java/io/nats/client/impl/NatsDispatcherWithExecutor.java
Added optional ability to make the dispatcher deliver messages using the task executor instead of with a blocking call.
=> Optional dispatching with executor instead of blocking

build.gradle, src/examples/java/io/nats/examples/ExampleAuthHandler.java, src/main/java/io/nats/client/NKey.java, src/main/java/io/nats/client/impl/FileAuthHandler.java, src/main/java/io/nats/client/impl/StringAuthHandler.java, src/test/java/io/nats/client/NKeyTests.java
The NKey library was extracted to another repo and was then this project was made to depend on that library and also keep the existing library. Since there is zero functionality change, this is being reverted to ensure that there is absolutely no backward compatibility issues, even though there probably wasn't.
=> Revert NKey class extraction to ensure no backward compatibility issues.

src/main/java/io/nats/client/impl/NatsConnection.java, src/test/java/io/nats/client/impl/AuthAndConnectTests.java
In the unlikely but possible scenario where the reader/writer threads would call into `handleCommunicationIssue` twice, `disconnecting` could be set by the other thread just before going into `reconnect()`.
This would cause these lines to exit the reconnecting loop:
```java
if (isDisconnectingOrClosed() || this.isClosing()) {
keepGoing = false;
}
```
Which would then call into `close()` here:
```java
if (!isConnected()) {
this.close();
return;
}
```
This PR fixes that by not checking the `disconnected` flag, instead checking `isClosed() || isClosing()` as it was [before this commit](https://github.com/nats-io/nats.java/commit/c4d50b2e30c13164dd08a59d3a2d7a936040e8aa#diff-bbcf614ee7ee4ccd15b22d1f95fa40e4e642098386b6d1d14127dab5968d89feR204).
Related to issue reported on Slack: …
=> Fix reconnect() calls close() when simultaneously 'disconnecting' in another thread

src/main/java/io/nats/client/impl/MessageManager.java, src/main/java/io/nats/client/impl/MessageQueue.java, src/main/java/io/nats/client/impl/NatsConnectionWriter.java, src/main/java/io/nats/client/impl/NatsConsumer.java, src/main/java/io/nats/client/impl/NatsDispatcher.java, src/main/java/io/nats/client/impl/NatsSubscription.java, src/test/java/io/nats/client/impl/JetStreamGeneralTests.java, src/test/java/io/nats/client/impl/MessageManagerTests.java, src/test/java/io/nats/client/impl/MessageQueueBenchmark.java, src/test/java/io/nats/client/impl/MessageQueueTests.java
The offer timeout was hard-coded to 5 seconds. This change takes the request cleanup intervalfrom Options and takes 95% of that time.
* request cleanup interval is the time allotted for request reply messages to sit un-responded to in the internal map.
* offer timeout is the time to offer an incoming reply response message to be enqueued. It used to be the same as the default request cleanup interval. If it takes too long to be enqueued, the waiting handler is going to be cleaned up anyway.
=> Offer timeout millis no longer hardcoded

src/main/java/io/nats/client/KeyValue.java, src/main/java/io/nats/client/impl/NatsKeyValue.java, src/test/java/io/nats/client/impl/KeyValueTests.java
https://github.com/nats-io/nats-architecture-and-design/issues/271
https://github.com/nats-io/nats.java/issues/1091
1. New public methods in KeyValue for delete and purge with optimistic concurrency support:
```
void delete(String key, long expectedRevision) throws IOException, JetStreamApiException;
void purge(String key, long expectedRevision) throws IOException, JetStreamApiException;
```
2. New unit test `testAtomicDeleteAtomicPurge` with positive and negative cases.
I wasn't able to get a 100% pass of unit tests in my environment, but the `KeyValueTests` suite (including the new UT) was 100% passing.
=> KeyValue atomic delete and purge methods.

src/examples/java/io/nats/examples/jetstream/NatsJsManageConsumers.java, src/main/java/io/nats/client/JetStreamManagement.java, src/main/java/io/nats/client/api/ConsumerConfiguration.java, src/main/java/io/nats/client/api/ConsumerInfo.java, src/main/java/io/nats/client/api/ConsumerPauseRequest.java, src/main/java/io/nats/client/api/ConsumerPauseResponse.java, src/main/java/io/nats/client/impl/NatsJetStream.java, src/main/java/io/nats/client/impl/NatsJetStreamManagement.java, src/main/java/io/nats/client/support/ApiConstants.java, src/main/java/io/nats/client/support/NatsJetStreamConstants.java, src/test/java/io/nats/client/api/ConsumerConfigurationTests.java, src/test/java/io/nats/client/api/ConsumerInfoTests.java, src/test/java/io/nats/client/api/ResponseTests.java, src/test/java/io/nats/client/impl/ConsumerConfigurationComparerTests.java, src/test/java/io/nats/client/impl/JetStreamManagementTests.java, src/test/java/io/nats/client/utils/TestBase.java, src/test/resources/data/ConsumerInfo.json, src/test/resources/data/ConsumerPauseResponse.json, src/test/resources/data/ConsumerResumeResponse.json
Resolves https://github.com/nats-io/nats.java/issues/1084
Adds support for pausing and resuming consumers.
- The `JetStreamManagement` now has methods to `jsm.pauseConsumer(stream, consumer, pauseUntil)`, as well as `jsm.resumeConsumer(stream, consumer)`.
- An example for the above is also added to `src/examples`.
- `ConsumerConfiguration`/builder now has support for setting `pauseUntil` as well. Allowing to set it during consumer creation.
An optional addition (not implemented now) could be:
- Not allowing pause/resume when not running the appropriate server version. Throwing a custom exception, instead of a timeout (since the server is not listening to the subjects). What do you think?
=> Implement Consumers Pause 

src/examples/java/io/nats/examples/chaosTestApp/Output.java, src/main/java/io/nats/client/NUID.java, src/main/java/io/nats/client/impl/MessageManager.java, src/main/java/io/nats/client/impl/NatsConnectionWriter.java, src/main/java/io/nats/client/impl/NatsConsumerContext.java, src/main/java/io/nats/client/impl/NatsOrderedConsumerContext.java, src/main/java/io/nats/client/impl/NatsServerPool.java, src/main/java/io/nats/client/impl/NatsStreamContext.java, src/main/java/io/nats/client/impl/PullMessageManager.java, src/main/java/io/nats/client/support/WebSocket.java, src/main/java/io/nats/service/Service.java, src/test/java/io/nats/client/impl/ReconnectTests.java, src/test/java/io/nats/client/impl/TestHandler.java, src/test/java/io/nats/client/support/WebsocketSupportClassesTests.java
* Use ReentrantLock in place of synchronized since it's better for virtual threads and equally if not more performant.
* Ensure consumer context implementation is thread safe and switch to reentrant lock instead of synchronized.
=> ReentrantLock instead of synchronized

README.md, src/main/java/io/nats/client/impl/NatsConnection.java, src/test/java/io/nats/client/impl/JetStreamPubTests.java
If multiple treads publish messages at the same time, some messages may not be published because the inboxDispatcher is not started yet.  Change updates NatsConnection to ensure the inboxDispatcher is started prior to publishing messages.
Fixes #1065
=> Ensure NatsConnection inboxDispatcher is started prior to publishing messages

build.gradle, src/main/java/io/nats/client/Options.java, src/main/java/io/nats/client/impl/DataPort.java, src/main/java/io/nats/client/impl/NatsConnection.java, src/main/java/io/nats/client/impl/NatsConnectionReader.java, src/main/java/io/nats/client/impl/SocketDataPort.java, src/main/java/io/nats/client/impl/SocketDataPortWithWriteTimeout.java
Execute `forceClose` with an executor task inside `forceReconnect`. This prevents the force reconnect behavior from being blocked if close blocks.
---
In the SocketDataPortWithWriteTimeout implementation of the timeout watcher task:
1. Call the `forceReconnect` directly instead of running it on an executor task thread. It's already running on an executor task thread because that's where the watcher runs.
2. Removed the call to close the output stream of the socket. It's going to get closed anyway when the socket gets closed.
---
Added an `Options.socketSoLinger(int socketSoLinger)` for the user to set the underlying `socket.setSoLinger()`. This will be used in normal close operations. If a `forceClose` is requested, any option value supplied will be overridden with `setSoLinger(true, 0)` …
=> Improve socket close behavior

src/main/java/io/nats/client/Options.java, src/main/java/io/nats/client/impl/ListRequestEngine.java, src/main/java/io/nats/client/impl/NatsConnectionReader.java, src/main/java/io/nats/client/impl/NatsMessage.java, src/main/java/io/nats/client/support/JsonUtils.java, src/main/java/io/nats/client/support/JsonValueUtils.java, src/test/java/io/nats/client/OptionsTests.java, src/test/java/io/nats/client/PublishTests.java, src/test/java/io/nats/client/utils/TestBase.java, src/test/resources/data/utf8-test-strings.txt
For https://github.com/nats-io/nats.java/issues/1143
=> UTF subject support

src/main/java/io/nats/client/Connection.java, src/main/java/io/nats/client/api/MessageGetRequest.java, src/main/java/io/nats/client/impl/DataPort.java, src/main/java/io/nats/client/impl/Headers.java, src/main/java/io/nats/client/impl/NatsConsumer.java, src/main/java/io/nats/client/impl/NatsObjectStore.java, src/main/javadoc/overview.html
This is a test edit to verify style guides. 
Starting to make good on my promise to improve the documentation. 
Purpose:
1. Point users to the recommended (new) way of using Jetstream
2. Add more example code snipplets
3. Make sure such guidelines and code snipplet appear as early as possible in the developers journey. In this case on the Connection class. 
4. More detailed examples would then be in ConsumerContext and StreamContext
=> Recommended (new) APIs and more example code

src/main/java/io/nats/client/impl/NatsDispatcher.java, src/main/java/io/nats/client/impl/NatsDispatcherWithExecutor.java
Resolves https://github.com/nats-io/nats.java/issues/1198
We could handle the `Error` in the `ErrorListener` just like the `Exception` is handled.
But, an `Error` is likely to not be recoverable so probably stopping the dispatcher is the way to go? Just need to log that it happened.
=> Catch errors in Dispatchers and log

src/main/java/io/nats/client/impl/NatsConnection.java
This fixes an issue where on force reconnect the original threads of the reader and writer become parked, making them unavailable for other uses, eventually freezing the client.
=> During forceReconnect, ensure reader/writer is stopped before continuing

src/main/java/io/nats/client/impl/NatsConnection.java, src/test/java/io/nats/client/ConnectTests.java
If we'd call `handleCommunicationIssue` the `tryingToConnect` would be set to `true`.
Then if `reconnect()` was called it would check if `tryingToConnect` was not set, but because we did set it before we didn't reconnect.
Using `reconnectImpl` bypasses that guard, since we're already in `tryingToConnect` state.
=> While `handleCommunicationIssue`, `closeSocket` should use reconnect impl otherwise `tryingToConnect` will guard

src/main/java/io/nats/client/impl/NatsConnection.java
When doing a request through `requestFutureInternal` we'd publish the message into the outgoing write queue, and immediately after call `writer.flushBuffer()`.
Due to the message needing to go through the outgoing message queue, which takes a small amount of time, the `flushBuffer` would be done first and before our message got written to the `dataPort`.
Removing the call to `writer.flushBuffer()` since it doesn't actually flush our message/request.
Signed-off-by: Maurice van Veen <github@mauricevanveen.com>
=> Remove redundant `writer.flushBuffer()` call

src/main/java/io/nats/client/Connection.java, src/main/java/io/nats/client/impl/NatsConnectionWriter.java
* Instead of using writerLock around flushBuffer (socket flush), set a flag to tell the sendMessageBatch to flushBuffer after a write, instead of locking around send.
=> Removing writerLock in favor of setting a flag to call flushBuffer

src/main/java/io/nats/client/impl/MessageQueue.java, src/main/java/io/nats/client/impl/NatsConnection.java, src/main/java/io/nats/client/impl/NatsConnectionReader.java, src/main/java/io/nats/client/impl/NatsConnectionWriter.java, src/main/java/io/nats/client/impl/NatsConsumer.java, src/main/java/io/nats/client/impl/NatsDispatcher.java, src/main/java/io/nats/client/impl/NatsDispatcherWithExecutor.java, src/main/java/io/nats/client/impl/NatsJetStreamImpl.java
Add missing `Thread.currentThread().interrupt();` calls where `InterruptedException` was caught.
=> When interrupted call interrupt

src/main/java/io/nats/client/impl/NatsConnection.java, src/test/java/io/nats/client/impl/RequestTests.java
If a future would be cancelled outside of `cleanResponses`, calling `future.get()` would throw a `CancellationException`.
This exception was not caught, breaking future cleanup.
=> Fix `cleanResponses` must handle cleaning up cancelled future

src/main/java/io/nats/client/impl/NatsFeatureBase.java, src/main/java/io/nats/client/impl/NatsJetStream.java, src/main/java/io/nats/client/impl/NatsJetStreamImpl.java, src/main/java/io/nats/client/impl/NatsJetStreamManagement.java
JetStream implementation code relies on the the timeout, first from any supplied JetStreamOptions, second from connection options. This just simplifies, so code is not duplicated and can be retrieved via one method that understands the priority.
=> Easier access to timeout in JetStream implementations

src/main/java/io/nats/client/impl/NatsMessageConsumer.java
Fixed exception handling. Making sure the original connection exception is visible.
=> Fix: exception on simple consume when disconnected immediately

src/main/java/io/nats/client/Options.java, src/main/java/io/nats/client/impl/NatsConnection.java, src/test/java/io/nats/client/OptionsTests.java
=> feat(nats-connection): implement named executor thread factories

src/main/java/io/nats/client/Options.java
Added the ability for the Options builder to accept properties for the Executor Service implementation, the Connect thread executor factory and the Callback thread executor factory.
=> Executor and Executor Factories in Options can be created via properties

src/main/java/io/nats/client/JetStream.java, src/main/java/io/nats/client/MessageConsumer.java
It was unclear what stop() did versus close() - For non pull based consumers (Push or Ordered) stop() has no apparent effect at all.
=> Docs - close() versus stop() in MessageConsumer

src/main/java/io/nats/client/support/JsonUtils.java, src/main/java/io/nats/service/EndpointContext.java, src/main/java/io/nats/service/InfoResponse.java, src/main/java/io/nats/service/Service.java, src/main/java/io/nats/service/ServiceBuilder.java, src/main/java/io/nats/service/StatsResponse.java, src/test/java/io/nats/service/ServiceTests.java
update_service_to_support_adding_endpoint_after_construction
=> feature: update_service_to_support_adding_endpoint_after_construction

src/main/java/io/nats/service/InfoResponse.java, src/main/java/io/nats/service/Service.java, src/main/java/io/nats/service/ServiceResponse.java, src/test/java/io/nats/service/ServiceTests.java
Additional testing. Minor tweaks.
=> Feature: Support adding service endpoint after construction (more)

src/main/java/io/nats/service/Endpoint.java, src/main/java/io/nats/service/EndpointContext.java, src/main/java/io/nats/service/ServiceEndpoint.java, src/test/java/io/nats/service/ServiceTests.java
Bug fix: internal endpoints should not be run in a queue group.
=> Service user endpoints can be run without queue groups.

build.gradle, dependencies.md, src/main/java/io/nats/client/NKey.java, src/test/java/io/nats/client/NKeyTests.java
net.i2p.crypto has a CVE https://nvd.nist.gov/vuln/detail/CVE-2020-36843 and is not being maintained. BouncyCastle is an industry standard well maintained library.
=> Replace net.i2p.crypto with BouncyCastle

build.gradle, dependencies.md, src/main/java/io/nats/client/NKey.java, src/test/java/io/nats/client/NKeyTests.java
net.i2p.crypto has a CVE https://nvd.nist.gov/vuln/detail/CVE-2020-36843 and is not being maintained. BouncyCastle is an industry standard well maintained library.
=> Replace ed25519 with BouncyCastle

src/main/java/io/nats/client/api/FeatureConfiguration.java, src/main/java/io/nats/client/api/KeyValueConfiguration.java, src/main/java/io/nats/client/support/NatsJetStreamConstants.java, src/test/java/io/nats/client/impl/KeyValueTests.java
Ensure that duplicate window is 
* never more than 2 minutes
* never greater than the max_age
=> KV TTL (stream max_age) versus stream duplicate_window

src/main/java/io/nats/client/BaseConsumeOptions.java
This is a recently added feature where you can create ConsumeOptions from json. The value for the expires in field was not properly set to the default value when not supplied in the json.
=> ConsumeOptions creation from json should use default, not minimum

src/main/java/io/nats/client/KeyValue.java, src/main/java/io/nats/client/MessageTtl.java, src/main/java/io/nats/client/PublishOptions.java, src/main/java/io/nats/client/api/KeyValueConfiguration.java, src/main/java/io/nats/client/api/KeyValueStatus.java, src/main/java/io/nats/client/api/StreamConfiguration.java, src/main/java/io/nats/client/impl/NatsKeyValue.java, src/main/java/io/nats/client/impl/NatsKeyValueManagement.java, src/main/java/io/nats/client/support/NatsKeyValueUtil.java, src/main/java/io/nats/client/support/Validator.java, src/test/java/io/nats/client/PublishOptionsTests.java, src/test/java/io/nats/client/impl/JetStreamPubTests.java, src/test/java/io/nats/client/impl/KeyValueTests.java, src/test/java/io/nats/client/support/ValidatorTests.java
Accept a per message ttl when creating a kv. Implements [ADR-43](https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-43.md)
```
public long create(String key, byte[] value, MessageTtl messageTtl) throws IOException, JetStreamApiException
```
=> KV Limit Marker

src/main/java/io/nats/client/impl/NatsJetStreamSubscription.java, src/main/java/io/nats/client/impl/OrderedMessageManager.java, src/main/java/io/nats/client/impl/PullMessageManager.java, src/main/java/io/nats/client/impl/PullOrderedMessageManager.java, src/main/java/io/nats/client/support/Status.java
also some api doc cleanup and added a constant.
=> Better workflow for leadership change while simplified consuming.

src/main/java/io/nats/client/Options.java, src/test/java/io/nats/client/OptionsTests.java
Useful when using time-limited tokens to authenticate via auth callout.
When using `Options.Builder#token` a later reconnection might attempt to reauthenticate with an expired token.
With `Options.Builder#tokenSupplier` nats.java will invoke the supplier to get a fresh token before each connection attempt.
=> Add connection auth token supplier option

build.gradle
Prevent long-running test failures to help figure test not finishing.
=> Set the test timeout default to 3 minutes.

src/examples/java/io/nats/examples/jetstream/simple/OrderedMessageConsumerExample.java, src/main/java/io/nats/client/impl/MessageManager.java, src/main/java/io/nats/client/impl/NatsConsumerContext.java, src/main/java/io/nats/client/impl/NatsFetchConsumer.java, src/main/java/io/nats/client/impl/NatsMessageConsumer.java, src/main/java/io/nats/client/impl/NatsMessageConsumerBase.java, src/main/java/io/nats/client/impl/PullOrderedMessageManager.java, src/main/java/io/nats/client/support/ScheduledTask.java, src/test/java/io/nats/client/impl/SimplificationTests.java, src/test/java/io/nats/client/support/ScheduledTaskTests.java
Much better. 
* It was not the scheduler change that was the error, it was a change in workflow
* Added a unit test to simulate the error found. 
* Added a simplified Ordered Consumer example
* fixed an issue that was pre-existing which may have caused simplified ordered consumers to not reset correctly after disconnnect.
=> Fix heartbeat timer handling broken when replacing timer with scheduler.

build.gradle, src/main/java/io/nats/client/impl/NatsDispatcher.java, src/main/java/io/nats/client/impl/NatsDispatcherWithExecutor.java, src/main/java/io/nats/client/impl/NatsSubscription.java, src/main/java/io/nats/client/impl/NatsWatchSubscription.java, src/test/java/io/nats/client/SubscriberTests.java, src/test/java/io/nats/client/impl/AuthViolationDuringReconnectTest.java
Fixes #1232
The dispatcher api allows subscribe 
1. with a subject and no message handler, `subscribe("foo");`, in which case it will use the message handler provided when the dispatcher was created.
2. with a subject plus and a message handler, `subscribe("foo", nonDefaultHandler);`.
If you `unsubscribe("foo")`, the dispatcher currently only unsubscribes the subscription with the default handler, meaning if you had subscribed with a non default handler, that subscriptions did not get unsubscribed. (That was the behavior reported in #1232)
The dispatcher should unsubscribe for all handlers, default or otherwise, for a subject.
You can only have one subscription for a subject with the default handler (otherwise you just get multiple copies of the same message to that handler) but you can …
=> Fix core unsubscribe by subject

src/main/java/io/nats/client/impl/NatsConnection.java, src/main/java/io/nats/client/impl/NatsConsumer.java
To avoid overflow issue while comparing elapsed time against a timeout,
given
```
long timeoutNanos = <some timeout value>
long startTime = System.nanoTime;
long stopTime = System.nanoTime + timeoutNanos;
```
use
```
if (System.nanoTime() - startTime >= timeoutNanos)
```
instead of
```
if (System.nanoTime() >= stopTime)
```
and use
```
while (System.nanoTime() - startTime < timeoutNanos)
```
instead of
```
while (System.nanoTime() < stopTime)
```
=> Fix timeout computing to address possible nano time overflow

src/main/java/io/nats/client/impl/Headers.java, src/test/java/io/nats/client/impl/HeadersTests.java
**Headers.java**
1. I actually came to add toString(), required for debugging and logging;
Then I saw and:
2. Fixed nullability issues.
3. Replaced inefficient keySet() + Map.get() pattern with entrySet().
4. Fixed broken forEach loop; added a failing test to confirm the issue before the fix.
5. Replaced val.chars() with a more efficient for-loop and charAt().
6. Removed "redundant" `private final boolean readOnly` field; replaced with another check.
7. Finally, I have added missing tests.
---
I really don't have time for several one-line PRs 😭🙏
This PR is obvious and not bigger than your recent PRs.
I open to your questions, critic, and recommendations for improvement 🤝
-----
PS: Some java quirks (why I have changed those lines)
1) Collections.unmodifiableMap isn't completely …
=> Headers +toString(), fixes

src/main/java/io/nats/client/api/ObjectInfo.java, src/main/java/io/nats/client/api/ObjectMeta.java, src/main/java/io/nats/client/api/ObjectMetaOptions.java, src/test/java/io/nats/client/api/ObjectStoreApiTests.java, src/test/resources/data/ObjectInfo.json
The java client has ObjectMeta Headers, which is a map of string (key) to list of strings (value), but does not have the additional, almost identical field of metadata, which is a map of string (key) to string (value).
=> ObjectMeta metadata

src/main/java/io/nats/client/JetStreamSubscription.java
The current javadoc for the `maxWait` parameter in both `fetch()` method overloads incorrectly states that it's "the maximum time to wait for the first message." This is misleading as it suggests the timeout only applies to receiving the initial message.
Updated the parameter descriptions to clarify that `maxWait`/`maxWaitMillis` is "the maximum time to wait to collect messages for the batch," which accurately reflects that the timeout governs the entire batch collection operation.
- Updated `@param maxWait` description in javadoc for `fetch(int batchSize, Duration maxWait)` method
- Updated `@param maxWaitMillis` description in javadoc for `fetch(int batchSize, long maxWaitMillis)` method
This change improves API documentation clarity for developers using JetStream pull subscriptions.
=> Clarify documentation for JetStreamSubscription

build.gradle
For more information, please see [CVE-2025-9341](https://nvd.nist.gov/vuln/detail/CVE-2025-9341) and Bouncycastle [resolution](https://github.com/bcgit/bc-java/wiki/CVE%E2%80%902025%E2%80%909341).
=> Update version of `bouncycastle` to resolve CVE-2025-9341

src/main/java/io/nats/client/ErrorListener.java, src/main/java/io/nats/client/JetStreamSubscription.java, src/main/java/io/nats/client/impl/NatsJetStreamSubscription.java, src/test/java/io/nats/client/impl/JetStreamTestBase.java
Exposed StreamName to NatsJetstreamSubscription and extended ErrorListener to log it.
The change is fairly simple and has not hidden dependencies. The NatsJetstreamSubscription was only implemented once. The streamName was already present (but protected).
=> Exposed StreamName

src/main/java/io/nats/client/impl/NatsConnectionWriter.java, src/main/java/io/nats/client/impl/SocketDataPort.java
Fixing issue reporting message count (length) instead of bytes
=> Properly return size in bytes

src/main/java/io/nats/client/ConnectionListener.java, src/main/java/io/nats/client/impl/NatsConnection.java
A new method with a default implementation is added to ConnectionListener. The caller of connection listeners now calls the new method allowing implementors to have extra details about the uri related to this connection event. This information was not always available from the Connection object server info, for instance on reconnect, the connection will be stale, and the details contain information about the uri trying to be connected to and the host uri if the try to connect uri is an ip address resolved from the host uri.
```
default void connectionEvent(Connection conn, Events type, String uriDetails) {
connectionEvent(conn, type);
}
```
=> Improve ConnectionListener

src/main/java/io/nats/client/ConnectionListener.java, src/main/java/io/nats/client/impl/NatsConnection.java
* Collect the time of the event to send to the listener, giving better resolution that the event being received on a callback.
=> ConnectionListener event time

src/main/java/io/nats/client/JetStream.java
fix: correct class name typo from Jetstream to JetStream in NATS client JetStream.java
=> Fixed the Typo in the Example Code
