nats-io/nats.java

src/main/java/io/nats/client/AbstractConnection.java

Change to Javadoc to mention SyncSubscription instead of AsyncSubscription. Also using {@link} instead of {@code}.

Change Javadoc to mention SyncSubscription instead of AsyncSubscription.

---

README.md

I could be wrong but I think this is the right fix here - it works for me at least.

Fix error example code

---

pom.xml
src/main/java/io/nats/client/ConnectionFactory.java
src/main/java/io/nats/client/ConnectionImpl.java
src/main/java/io/nats/client/TCPConnectionFactory.java
src/test/java/io/nats/client/ConnectionFactoryTest.java
src/test/java/io/nats/client/ConnectionTest.java
src/test/java/io/nats/client/ParserPerfTest.java
src/test/java/io/nats/client/ParserTest.java
src/test/java/io/nats/client/ProtocolTest.java
src/test/java/io/nats/client/TCPConnectionFactoryMock.java
src/test/java/io/nats/client/TLSTest.java

Changes mock TCPConnection injection strategy to pass a factory vs. a connection.

Inject tcp conn fixes #37

---

src/main/java/io/nats/client/ConnectionImpl.java
src/test/java/io/nats/client/TLSTest.java

This is a WIP and I'm starting the PR with a TLS reconnect test. Can you please validate @mcqueary?

Fix TLS reconnection

---

.travis.yml
.travis/deploy.sh
pom.xml
src/test/java/io/nats/client/ConnectionFactoryTest.java

Move jacoco and coveralls support back into local POM, plus various other tweaks to maven config and executions.

Fix coveralls

---

.travis.yml
src/main/java/io/nats/client/ConnectionImpl.java
src/main/java/io/nats/client/Parser.java

Adds exception handling and reconnect logic in case of `NumberFormatException`.

Long exception fixes #30

---

src/test/java/io/nats/client/TCPConnectionMock.java

Added null checks to prevent NPEs in ConnectionFactoryTest#bounce()

---

src/main/java/io/nats/benchmark/Benchmark.java
src/main/java/io/nats/client/Channel.java
src/test/java/io/nats/client/NATSServer.java

Reduces visibility of class to package, in anticipation of removal.

Reduce channel visibility

---

src/it/java/io/nats/client/ITBasicTest.java
src/it/java/io/nats/client/ITConnectionTest.java
src/it/java/io/nats/client/ITReconnectTest.java
src/main/java/io/nats/client/ConnectionImpl.java
src/main/java/io/nats/client/SubscriptionImpl.java
src/main/java/io/nats/client/SyncSubscriptionImpl.java
src/test/java/io/nats/client/ConnectionImplTest.java
src/test/java/io/nats/client/UnitTestUtilities.java

Also updates some test conventions.

Simplify executors

---

CHANGELOG.md
src/main/java/io/nats/client/AbstractConnection.java
src/main/java/io/nats/client/ConnectionImpl.java

Add isTlsRequired() and isAuthRequired()

---

src/main/java/io/nats/client/ConnectionImpl.java
src/test/java/io/nats/client/ParserTest.java

When connecting to a server, the received INFO may contain an array of URLs. The current code was adding those and then shuffling the entire pool (if NoRandomize is false). This is wrong since the connect (and reconnect) loop would then potentially skip never tried servers and try again servers that had just failed.
See also [go-nats#260](https://github.com/nats-io/go-nats/pull/260)

Fix srv pool shuffle

---

src/main/java/io/nats/client/ConnectionImpl.java
src/test/java/io/nats/client/ConnectionImplTest.java

Fixes #105 
I don't code a lot in java, so please let me know if I can make this more idiomatic. Thanks!

Catch IOException on output stream when force flushing socket

---

README.md

@nats-io/core I'm putting these examples into a currently private repo (java-nats-examples), where they will be compilable and testable. I'll add issues for the remainder of the java examples to be added there.

updated based on suggestions from @grange74

---

.travis/deploying.md
CHANGELOG.md
README.md
build.gradle
src/main/java/io/nats/client/Options.java
src/main/java/io/nats/client/impl/MessageQueue.java

Cleanup for rename to nats.java

---

src/main/java/io/nats/client/Options.java
src/main/java/io/nats/client/impl/NatsConnection.java
src/main/java/io/nats/client/impl/NatsMessage.java
src/test/java/io/nats/client/AuthTests.java
src/test/java/io/nats/client/OptionsTests.java
src/test/java/io/nats/client/impl/MessageProtocolCreationBenchmark.java
src/test/java/io/nats/client/impl/MessageQueueBenchmark.java
src/test/java/io/nats/client/impl/MessageQueueTests.java
src/test/java/io/nats/client/impl/NatsMessageTests.java
src/test/java/io/nats/client/impl/ReconnectTests.java

This ended up being pretty invasive since it required carrying char arrays throught the other code to make sure we don't "toString" the password.
All tests are running but some of the API is now deprecated.

Converted password/user/token to char arrays

---

src/main/java/io/nats/client/Message.java

Resolves #283
Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

[FIXED] Javadoc of Message.getSID() [ci skip]

---

src/examples/java/io/nats/examples/examples.md

fix broken link

---

README.md
src/main/java/io/nats/client/Nats.java

Version updates

---

src/main/java/io/nats/client/impl/NatsConnection.java

Removed several print statements from debugging

---

CHANGELOG.md
README.md
build.gradle
src/main/java/io/nats/client/Nats.java
src/main/java/io/nats/client/impl/NatsConnection.java

Colin or Richard, this should update all the version files, can you merge and then tag the release sometime tomorrow. I don't want to do it super late. There is an issue requesting the release, so we can close that once this goes out.

Updated for version 2.6.8

---

src/main/java/io/nats/client/impl/NatsConnection.java

Finding that one took a while ...
Signed-off-by: Matthias Hanel <mh@synadia.com>

Printing trace when NUID initialization takes long

---

CHANGELOG.md
README.md
build.gradle
src/main/java/io/nats/client/Nats.java

Version bump to 2.7.0 for release.

Version bump to 2.7.0

---

build.gradle
src/main/java/io/nats/client/Nats.java

Jetstream additions warrant a minor version bump.

Version bump to 2.9.0

---

src/examples/java/io/nats/examples/ExampleUtils.java
src/examples/java/io/nats/examples/NatsJsPub.java
src/examples/java/io/nats/examples/NatsJsSub.java
src/examples/java/io/nats/examples/NatsJsSubCb.java

Also added additional comments.

Add dispatcher example

---

README.md
src/examples/java/io/nats/examples/examples.md

Update the readme and examples.md for Jetstream.

Update readme with Jetstream

---

src/examples/java/io/nats/examples/ExampleArgs.java
src/examples/java/io/nats/examples/NatsJsSubAttach.java
src/examples/java/io/nats/examples/examples.md
src/main/java/io/nats/client/StreamConfiguration.java

* A minor update to stream defaults
* Add an attach example

Jetstream Updates

---

src/examples/java/io/nats/examples/NatsJsPubDirect.java
src/examples/java/io/nats/examples/NatsJsSubAttachDirect.java
src/examples/java/io/nats/examples/examples.md
src/main/java/io/nats/client/SubscribeOptions.java
src/main/java/io/nats/client/impl/NatsJetStream.java

Adds examples of a direct publish and direct attach to a consumer.
A few bug fixes as well.
cc /@scottf

Add Direct examples

---

src/main/java/io/nats/client/ConsumerConfiguration.java
src/test/java/io/nats/client/ConsumerConfigurationTests.java

Some API fixes and correlated test updates.

Consumer Configuration Fixes

---

dependencies.md

List dependencies and their licenses.

Add dependencies list

---

src/main/java/io/nats/client/JetStreamOptions.java
src/main/java/io/nats/client/SubscribeOptions.java
src/main/java/io/nats/client/impl/NatsJetStream.java
src/test/java/io/nats/client/JetstreamTests.java

Some minor fixes and updates, and adds tests to check for #388.
/CC @scottf

Various updates and tests

---

src/examples/java/io/nats/examples/NatsJsPullFetch.java
src/examples/java/io/nats/examples/NatsJsPullReceive.java
src/examples/java/io/nats/examples/NatsJsReceive.java
src/main/java/io/nats/client/JetStreamSubscription.java
src/main/java/io/nats/client/impl/DateTimeUtils.java
src/main/java/io/nats/client/impl/Headers.java
src/main/java/io/nats/client/impl/JetStreamApiResponse.java
src/main/java/io/nats/client/impl/JsPrefixManager.java
src/main/java/io/nats/client/impl/JsonUtils.java
src/main/java/io/nats/client/impl/NatsConnection.java
src/main/java/io/nats/client/impl/NatsJetStreamSubscription.java
src/main/java/io/nats/client/impl/NatsMessage.java
src/main/java/io/nats/client/support/RandomUtils.java
src/main/java/io/nats/client/support/Validator.java
src/test/java/io/nats/client/impl/ByteArrayBuilderTests.java
src/test/java/io/nats/client/impl/HeadersTests.java
src/test/java/io/nats/client/impl/JetStreamApiResponseTests.java
src/test/java/io/nats/client/impl/JetStreamPullTests.java
src/test/java/io/nats/client/impl/JetStreamTestBase.java
src/test/java/io/nats/client/impl/NatsJetStreamMetaDataTests.java
src/test/java/io/nats/client/impl/NatsMessageTests.java
src/test/resources/data/ErrorResponses.json.txt

This PR has one piece of functionality added the pull receive method. It also has several test coverage improvements.

pull-receive

---

src/main/java/io/nats/client/MessageInfo.java
src/main/java/io/nats/client/impl/NatsJetStreamConstants.java

message management, handler tests 2

---

build.gradle
src/examples/java/io/nats/examples/NatsReply.java
src/examples/java/io/nats/examples/NatsReq.java
src/main/java/io/nats/client/Nats.java
src/main/java/io/nats/client/impl/NatsConnection.java
src/main/java/io/nats/client/impl/NatsJetStream.java
src/main/java/io/nats/client/impl/NatsStatistics.java
src/main/java/io/nats/client/package-info.java
src/main/java/io/nats/client/support/NatsRequestCompletableFuture.java
src/test/java/io/nats/client/ConnectTests.java
src/test/java/io/nats/client/impl/JetStreamManagementTests.java
src/test/java/io/nats/client/impl/JetStreamPubTests.java
src/test/java/io/nats/client/impl/ReconnectTests.java
src/test/java/io/nats/client/impl/RequestTests.java
src/test/java/io/nats/client/utils/TestBase.java
src/test/resources/js_authorization.conf
src/test/resources/js_authorization_token.conf

also some unit tests on jetstream accounts

improve cleanup of async responses

---

src/examples/java/io/nats/examples/autobench/AutoBenchmark.java
src/examples/java/io/nats/examples/autobench/LatencyBenchmark.java
src/examples/java/io/nats/examples/autobench/NatsAutoBench.java
src/examples/java/io/nats/examples/jsmulti/Arguments.java
src/examples/java/io/nats/examples/jsmulti/JsMulti.java
src/examples/java/io/nats/examples/jsmulti/Stats.java

1. multi - make stats and args more accessible in case user wants to customize args or use stats for their own purposes 
2. multi - remove payload generation from timing in case they want to override
3. multi - ability to report to file and extract totals
4. auto bench - latency reporting more readable

js multi improvements to help re-use

---

src/examples/java/io/nats/examples/jetstream/NatsJsPushSubFlowControl.java
src/test/java/io/nats/client/impl/JetStreamPushTests.java

making sure unit test and example exercise use of both pending message and byte limits

more flow control

---

src/examples/java/io/nats/examples/jetstream/NatsJsPushSubFilterSubject.java
src/main/java/io/nats/client/api/ConsumerConfiguration.java
src/main/java/io/nats/client/impl/NatsJetStream.java
src/test/java/io/nats/client/impl/JetStreamGeneralTests.java

filter subject was not working for ephemeral or new durable consumers

fixed filter subject

---

src/examples/java/io/nats/examples/README.md
src/examples/java/io/nats/examples/jetstream/NatsJsPushSubDeliverSubject.java
src/examples/java/io/nats/examples/jetstream/NatsJsPushSubFilterSubject.java
src/examples/java/io/nats/examples/jetstream/NatsJsPushSubFlowControl.java
src/examples/java/io/nats/examples/jetstream/NatsJsPushSubHeartbeat.java
src/examples/java/io/nats/examples/jetstream/NatsJsPushSubQueueDeliverSubject.java
src/examples/java/io/nats/examples/jetstream/NatsJsPushSubQueueDurable.java

fix examples based on better understanding of deliver subject

deliver subject

---

README.md

instructions for having OCSP stapling

ocsp stapling readme

---

CHANGELOG.md
README.md
build.gradle
src/examples/java/io/nats/examples/README.md
src/examples/java/io/nats/examples/autobench/NatsAutoBench.java
src/examples/java/io/nats/examples/jsmulti/README.md
src/examples/java/io/nats/examples/jsmulti/Usage.java
src/main/java/io/nats/client/Nats.java
src/main/java/io/nats/client/impl/Headers.java
src/main/java/io/nats/client/package-info.java
src/main/java/io/nats/client/support/IncomingHeadersProcessor.java
src/main/java/io/nats/client/support/NatsConstants.java
src/main/java/io/nats/client/support/Token.java
src/test/java/io/nats/client/impl/HeadersTests.java
src/test/java/io/nats/client/impl/JetStreamManagementTests.java
src/test/java/io/nats/client/impl/TLSConnectTests.java

create stream no subject, add then update consumer

unit test changes july '21

---

src/main/java/io/nats/client/JetStreamManagement.java
src/main/java/io/nats/client/KeyValueManagement.java
src/main/java/io/nats/client/PurgeOptions.java
src/main/java/io/nats/client/impl/NatsJetStreamManagement.java
src/main/java/io/nats/client/impl/NatsKeyValueManagement.java
src/main/java/io/nats/client/support/ApiConstants.java
src/test/java/io/nats/client/impl/JetStreamManagementTests.java
src/test/java/io/nats/client/impl/KeyValueTests.java

key value get bucket names , purge stream options

---

src/main/java/io/nats/client/JetStreamSubscription.java

Documentation valid since v2.3.4

document pull primitives as advanced

---

src/main/java/io/nats/client/PublishOptions.java
src/main/java/io/nats/client/impl/NatsJetStream.java
src/main/java/io/nats/client/support/NatsJetStreamConstants.java
src/test/java/io/nats/client/PublishOptionsTests.java
src/test/java/io/nats/client/impl/JetStreamPubTests.java

https://github.com/nats-io/nats-architecture-and-design/issues/8
Since server v2.3.4

Parity Issue 8 nats expected last subject sequence

---

src/main/java/io/nats/client/api/DeliverPolicy.java
src/main/java/io/nats/client/impl/NatsJetStreamMetaData.java
src/test/java/io/nats/client/api/NatsJetStreamMetaDataTests.java
src/test/java/io/nats/client/impl/JetStreamManagementTests.java
src/test/java/io/nats/client/impl/JetStreamTestBase.java
src/test/java/io/nats/client/impl/NatsJetStreamMessageTests.java
src/test/java/io/nats/client/impl/NatsJetStreamMetaDataTests.java

https://github.com/nats-io/nats-architecture-and-design/issues/49
backward compatible with server v2.3.4

Parity Issue 49 ack new tokens

---

README.md
build.gradle
src/examples/java/io/nats/examples/README.md
src/examples/java/io/nats/examples/autobench/NatsAutoBench.java
src/examples/java/io/nats/examples/jsmulti/README.md
src/examples/java/io/nats/examples/jsmulti/Usage.java
src/main/java/io/nats/client/Nats.java
src/main/java/io/nats/client/PublishOptions.java
src/main/java/io/nats/client/api/StreamConfiguration.java
src/main/java/io/nats/client/impl/NatsJetStream.java
src/main/java/io/nats/client/package-info.java
src/main/java/io/nats/client/support/Validator.java
src/test/java/io/nats/client/impl/JetStreamPubTests.java
src/test/java/io/nats/client/impl/KeyValueTests.java
src/test/java/io/nats/client/support/ValidatorTests.java
src/test/java/io/nats/client/utils/TestBase.java

1. bumping the version
2. proper kv key name check
3. handling that Nats-Expected-Last-Subject-Sequence value of zero has meaning

2.12.1 and kv key validation fix

---

README.md
build.gradle
src/examples/java/io/nats/examples/README.md
src/examples/java/io/nats/examples/autobench/NatsAutoBench.java
src/examples/java/io/nats/examples/jsmulti/README.md
src/examples/java/io/nats/examples/jsmulti/Usage.java
src/main/java/io/nats/client/Nats.java
src/main/java/io/nats/client/impl/NatsJetStream.java
src/main/java/io/nats/client/package-info.java
src/test/java/io/nats/client/impl/JetStreamGeneralTests.java

null or empty subject while subscribing / binding

---

src/main/java/io/nats/client/api/ConsumerConfiguration.java
src/main/java/io/nats/client/impl/NatsJetStream.java
src/main/java/io/nats/client/support/ApiConstants.java
src/main/java/io/nats/client/support/JsonUtils.java
src/test/java/io/nats/client/api/ConsumerConfigurationTests.java
src/test/java/io/nats/client/impl/ConsumerConfigurationComparerTests.java
src/test/java/io/nats/client/impl/JetStreamGeneralTests.java
src/test/resources/data/ConsumerConfiguration.json

https://github.com/nats-io/nats-architecture-and-design/issues/90

Consumer config support for max_batch, max_expire and inactive_threshold 

---

src/examples/java/io/nats/examples/jetstream/NatsJsPullSubMultipleWorkers.java
src/examples/java/io/nats/examples/jetstream/NatsJsPullSubQueueSimulated.java
src/test/java/io/nats/client/impl/JetStreamPushAsyncTests.java

queue simulated with durable pull consumer

Pull queue

---

src/main/java/io/nats/client/Message.java
src/main/java/io/nats/client/PurgeOptions.java
src/main/java/io/nats/client/api/ConsumerConfiguration.java
src/main/java/io/nats/client/impl/AckType.java
src/main/java/io/nats/client/impl/NatsJetStream.java
src/main/java/io/nats/client/impl/NatsJetStreamMessage.java
src/main/java/io/nats/client/impl/NatsMessage.java
src/main/java/io/nats/client/support/ApiConstants.java
src/main/java/io/nats/client/support/JsonUtils.java
src/main/java/io/nats/client/support/NatsConstants.java
src/test/java/io/nats/client/api/ConsumerConfigurationTests.java
src/test/java/io/nats/client/impl/ConsumerConfigurationComparerTests.java
src/test/java/io/nats/client/impl/JetStreamPushAsyncTests.java
src/test/java/io/nats/client/impl/JetStreamPushTests.java
src/test/java/io/nats/client/impl/JetStreamTestBase.java
src/test/java/io/nats/client/support/JsonUtilsTests.java
src/test/resources/data/ConsumerConfiguration.json

https://github.com/nats-io/nats-architecture-and-design/issues/89
Also change to Purge Options to use -1 instead of 0 as the default long so they don't get put in the outgoing json

Issue 89 nak delay and backoff

---

src/main/java/io/nats/client/support/NatsKeyValueUtil.java
src/test/java/io/nats/client/impl/KeyValueTests.java

[Issue #621](https://github.com/nats-io/nats.java/issues/621)

fixed kv key with dot as part of the key

---

build.gradle
src/main/java/io/nats/client/api/ConsumerInfo.java
src/main/java/io/nats/client/impl/NatsKeyValue.java
src/main/java/io/nats/client/impl/NatsKeyValueWatchSubscription.java

1. saves an entire round trip to the server b/c of getConsumerInfo. 
2. refactor added getCalculatedPending since needed in more than 1 place
3. better design of visitSubject which is used for methods keys / history / purge

tune kv subscribe supported functions keys / history / purge

---

src/main/java/io/nats/client/JetStreamSubscription.java
src/main/java/io/nats/client/PullRequestOptions.java

PullRequestOptions ARE CURRENTLY EXPERIMENTAL AND SUBJECT TO CHANGE.

---

src/main/java/io/nats/client/api/Placement.java
src/main/java/io/nats/client/support/Validator.java
src/test/java/io/nats/client/api/StreamConfigurationTests.java

There was never a public way for a user to create the Placement object, so you could not configure a stream with a placement.

ability for user to create a Placement object

---

README.md
build.gradle
src/examples/java/io/nats/examples/README.md

version should be bumped as soon as a release is done so merges to main build the correct snapshot.

bump version to 2.15.4

---

src/main/java/io/nats/client/impl/MessageManager.java
src/main/java/io/nats/client/impl/NatsConnection.java
src/main/java/io/nats/client/impl/NatsJetStream.java
src/main/java/io/nats/client/support/NatsRequestCompletableFuture.java
src/test/java/io/nats/client/impl/JetStreamOrderedConsumerTests.java
src/test/java/io/nats/client/impl/JetStreamPullTests.java
src/test/java/io/nats/client/impl/JetStreamTestBase.java

Fixing https://github.com/nats-io/nats.java/issues/658

only track duplicate responses when advanced tracking is on

---

src/examples/java/io/nats/examples/jetstream/NatsKeyValueFull.java
src/main/java/io/nats/client/KeyValueManagement.java
src/main/java/io/nats/client/impl/NatsKeyValueManagement.java
src/test/java/io/nats/client/impl/JetStreamManagementTests.java
src/test/java/io/nats/client/impl/KeyValueTests.java
src/test/java/io/nats/client/utils/TestBase.java

Provide an KeyValueManagement api to update the bucket config. https://github.com/nats-io/nats.java/issues/623

update bucket config

---

src/main/java/io/nats/client/JetStreamManagement.java
src/main/java/io/nats/client/impl/NatsJetStream.java
src/main/java/io/nats/client/impl/NatsJetStreamImplBase.java
src/main/java/io/nats/client/impl/NatsJetStreamManagement.java
src/test/java/io/nats/client/impl/JetStreamManagementTests.java

The ability to get a list of streams that match a subject filter

expose management getStreamNamesBySubjectFilter

---

src/main/java/io/nats/client/api/ConsumerConfiguration.java
src/main/java/io/nats/client/impl/NatsJetStream.java
src/main/java/io/nats/client/support/ApiConstants.java
src/test/java/io/nats/client/api/ConsumerConfigurationTests.java
src/test/java/io/nats/client/impl/ConsumerConfigurationComparerTests.java
src/test/java/io/nats/client/impl/JetStreamManagementTests.java
src/test/java/io/nats/client/impl/JetStreamPubTests.java
src/test/resources/data/ConsumerConfiguration.json

https://github.com/nats-io/nats.java/issues/688
support num_replicas and mem_storage in consumer configuration

Consumer replicas mem storage

---

src/examples/java/io/nats/examples/jetstream/NatsKeyValueFull.java
src/main/java/io/nats/client/KeyValue.java
src/main/java/io/nats/client/impl/NatsKeyValue.java
src/test/java/io/nats/client/impl/KeyValueTests.java

BUG FIX: kv get or get with revision against a deleted or purged key should not return an entry.

BUG FIX: kv get against a deleted or purged key

---

src/main/java/io/nats/client/api/MessageInfo.java
src/main/java/io/nats/client/api/Placement.java
src/main/java/io/nats/client/api/Republish.java
src/main/java/io/nats/client/api/StreamConfiguration.java
src/main/java/io/nats/client/support/ApiConstants.java
src/test/java/io/nats/client/api/StreamConfigurationTests.java
src/test/resources/data/StreamConfiguration.json

https://github.com/nats-io/nats-architecture-and-design/issues/139

implement republish

---

src/main/java/io/nats/client/ObjectStore.java
src/main/java/io/nats/client/api/ObjectInfo.java
src/main/java/io/nats/client/impl/NatsKeyValue.java
src/main/java/io/nats/client/impl/NatsObjectStore.java
src/test/java/io/nats/client/impl/KeyValueTests.java
src/test/java/io/nats/client/impl/ObjectStoreTests.java

Adding Object Store coverage found some minor issues so those were fixed.
Key Value added some coverage.

Object Store / Key Value coverage

---

src/main/java/io/nats/client/api/KeyValueConfiguration.java
src/test/java/io/nats/client/api/KeyValueConfigurationTests.java
src/test/java/io/nats/client/impl/JetStreamManagementTests.java

allow direct is user optional for kv

---

src/main/java/io/nats/client/api/KeyValueConfiguration.java
src/main/java/io/nats/client/impl/NatsKeyValueManagement.java
src/test/java/io/nats/client/api/KeyValueConfigurationTests.java

User is not allowed to set or modify in band.

allow direct is set to true on kv create bucket

---

src/main/java/io/nats/client/SubscribeOptions.java
src/main/java/io/nats/client/impl/NatsConnection.java
src/main/java/io/nats/client/impl/NatsJetStream.java
src/main/java/io/nats/client/impl/NatsJetStreamPullSubscription.java
src/main/java/io/nats/client/impl/NatsJetStreamSubscription.java
src/main/java/io/nats/client/impl/OrderedManager.java
src/main/java/io/nats/client/impl/PushMessageManager.java
src/test/java/io/nats/client/SubscribeOptionsTests.java
src/test/java/io/nats/client/impl/JetStreamOrderedConsumerTests.java
src/test/java/io/nats/client/impl/JetStreamPushTests.java
src/test/java/io/nats/client/impl/JetStreamTestBase.java
src/test/java/io/nats/client/impl/MessageManagerTests.java

1. reorganized managers to be hierarchy instead of individual. This makes it simpler to combine behavior and reduces overlap
2. For ordered consumers, missed heartbeats are handled by the manager instead of being raised to the user

Ordered Consumer Heartbeat Handling

---

src/main/java/io/nats/client/impl/ListRequestEngine.java

https://github.com/nats-io/nats.java/issues/781

changed handling of missing offset for paged

---

CHANGELOG.md
README.md
build.gradle
src/test/java/io/nats/client/api/StreamConfigurationTests.java
src/test/java/io/nats/client/impl/JetStreamManagementTests.java

Also modified tests to support regression testing.

Bump Version to 2.16.4

---

src/main/java/io/nats/client/Connection.java
src/main/java/io/nats/client/impl/NatsConnection.java
src/test/java/io/nats/client/ConnectTests.java
src/test/java/io/nats/client/impl/PingTests.java

https://github.com/nats-io/nats.java/issues/732

Implement RTT

---

src/main/java/io/nats/client/Connection.java
src/main/java/io/nats/client/impl/NatsConnection.java
src/test/java/io/nats/client/ConnectTests.java

https://github.com/nats-io/nats.java/issues/733

get client inet address

---

src/main/java/io/nats/client/api/LostStreamData.java
src/main/java/io/nats/client/api/StreamState.java
src/main/java/io/nats/client/support/ApiConstants.java
src/test/java/io/nats/client/api/StreamInfoTests.java
src/test/resources/data/StreamInfo.json

https://github.com/nats-io/nats.java/issues/737 support stream state -> lost stream data

stream state lost

---

src/main/java/io/nats/client/JetStreamOptions.java
src/main/java/io/nats/client/SubscribeOptions.java
src/main/java/io/nats/client/api/Error.java
src/main/java/io/nats/client/api/FeatureConfiguration.java
src/main/java/io/nats/client/api/KeyValueConfiguration.java
src/main/java/io/nats/client/api/KeyValueEntry.java
src/main/java/io/nats/client/api/Mirror.java
src/main/java/io/nats/client/api/Source.java
src/main/java/io/nats/client/api/SourceBase.java
src/main/java/io/nats/client/api/StreamConfiguration.java
src/main/java/io/nats/client/impl/NatsKeyValue.java
src/main/java/io/nats/client/impl/NatsKeyValueManagement.java
src/main/java/io/nats/client/impl/NatsKeyValueWatchSubscription.java
src/main/java/io/nats/client/impl/NatsWatchSubscription.java
src/main/java/io/nats/client/support/ApiConstants.java
src/main/java/io/nats/client/support/BuilderBase.java
src/main/java/io/nats/client/support/JsonUtils.java
src/main/java/io/nats/client/support/NatsJetStreamConstants.java
src/main/java/io/nats/client/support/NatsKeyValueUtil.java
src/test/java/io/nats/client/JetStreamOptionsTests.java
src/test/java/io/nats/client/api/StreamConfigurationTests.java
src/test/java/io/nats/client/impl/JetStreamManagementTests.java
src/test/java/io/nats/client/impl/JetStreamMirrorAndSourcesTests.java
src/test/java/io/nats/client/impl/KeyValueTests.java
src/test/java/io/nats/client/impl/RequestTests.java
src/test/java/io/nats/client/support/ByteArrayBuilderTests.java
src/test/java/io/nats/client/support/JsonUtilsTests.java
src/test/java/io/nats/client/utils/TestBase.java
src/test/resources/data/StreamConfiguration.json

https://github.com/nats-io/nats.java/issues/666

kv mirror support

---

src/examples/java/io/nats/examples/autobench/AutoBenchmark.java
src/main/java/io/nats/client/Nats.java
src/test/java/io/nats/client/OptionsTests.java

* Better development version string
* Better stream and subject names for auto benchmark

better dev version and autobench naming

---

build.gradle
src/main/java/io/nats/client/Connection.java
src/main/java/io/nats/client/JetStream.java
src/main/java/io/nats/client/impl/IncomingMessageFactory.java
src/main/java/io/nats/client/impl/NatsConnection.java
src/main/java/io/nats/client/impl/NatsJetStream.java
src/main/java/io/nats/client/impl/NatsJetStreamImplBase.java
src/main/java/io/nats/client/impl/PushMessageManager.java
src/test/java/io/nats/client/PublishTests.java
src/test/java/io/nats/client/impl/JetStreamPubTests.java
src/test/java/io/nats/client/impl/MessageManagerTests.java
src/test/java/io/nats/client/impl/NatsMessageTests.java
src/test/java/io/nats/client/impl/RequestTests.java
src/test/java/io/nats/client/support/WebsocketSupportClassesTests.java

https://github.com/nats-io/nats.java/issues/838

Fill in Publish / Request Header Gaps

---

build.gradle
src/test/java/io/nats/client/NatsTestServer.java
src/test/java/io/nats/client/impl/AdditionalConnectTests.java
src/test/java/io/nats/client/utils/TestBase.java

move to new server runner

---

README.md
src/examples/java/io/nats/examples/README.md
src/examples/java/io/nats/examples/jetstream/NatsJsPullSubFetch.java
src/examples/java/io/nats/examples/jetstream/NatsJsPullSubFetchUseCases.java
src/examples/java/io/nats/examples/jetstream/NatsJsPullSubIterate.java
src/examples/java/io/nats/examples/jetstream/NatsJsPullSubMultipleWorkers.java
src/examples/java/io/nats/examples/jetstream/NatsJsPushSubFlowControl.java
src/test/java/io/nats/client/impl/JetStreamPullTests.java

examples used to show durable was required for pull

Update docs and examples

---

src/main/java/io/nats/client/impl/NatsObjectStore.java

Addressing https://github.com/nats-io/nats.java/issues/851

use -1 to indicate end of stream, not lack of full buffer

---

src/main/java/io/nats/client/support/NatsUri.java
src/test/java/io/nats/client/OptionsTests.java

fix rehost for edge case when host name happens to be exactly the same as the protocol, i.e. the host name is "nats"

fix rehost

---

src/test/java/io/nats/client/ConnectTests.java
src/test/java/io/nats/client/impl/JetStreamPullTests.java
src/test/java/io/nats/client/impl/JetStreamPushTests.java
src/test/java/io/nats/client/impl/KeyValueTests.java
src/test/java/io/nats/client/impl/MessageManagerTests.java
src/test/java/io/nats/client/impl/ReconnectTests.java
src/test/java/io/nats/client/impl/TestHandler.java
src/test/java/io/nats/service/ServiceTests.java

* Regression issue, some test should not be run against server prior to 2.9.0
* Added some time for flappers

Test tuning

---

src/main/java/io/nats/client/support/JsonUtils.java
src/main/java/io/nats/client/support/JwtUtils.java
src/test/java/io/nats/client/support/JwtUtilsTests.java

https://github.com/nats-io/nats.java/issues/903

Enhance jwt utils

---

src/main/java/io/nats/client/support/ServerVersion.java
src/test/java/io/nats/client/api/ServerInfoTests.java
src/test/java/io/nats/client/api/StreamConfigurationTests.java
src/test/java/io/nats/client/impl/JetStreamGeneralTests.java
src/test/java/io/nats/client/impl/JetStreamManagementTests.java
src/test/java/io/nats/client/impl/KeyValueTests.java
src/test/java/io/nats/client/impl/SimplificationTests.java
src/test/java/io/nats/client/utils/TestBase.java

* Improved version check utils for use in regression testing to ensure features are tested properly against server versions.
* Fixed test running against 2.10 dev

Better testing checks against server versions

---

CHANGELOG.md
README.md
build.gradle

Housekeeping after a release preparing for next version.

Start 2.16.14

---

src/main/java/io/nats/client/api/Republish.java
src/main/java/io/nats/client/api/StreamConfiguration.java
src/main/java/io/nats/client/api/SubjectTransform.java
src/main/java/io/nats/client/support/ApiConstants.java
src/test/java/io/nats/client/api/StreamConfigurationTests.java
src/test/resources/data/StreamConfiguration.json

Add subject_transform to stream configuration. (Part 1.)
TBD Part 2/3/4 add subject_transform to mirror, source and republish

Subject Transform Stream Configuration Part 1

---

src/main/java/io/nats/client/BaseConsumeOptions.java
src/main/java/io/nats/client/impl/NatsFetchConsumer.java

Needed to differentiate between fetch no wait and fetch no wait with an expiration.

Make sure Fetch No Wait returns as soon as it gets 404/408

---

README.md
src/main/java/io/nats/client/impl/MessageQueue.java

* Updated code comments for MessageQueue
* Updated readme for info about forceReconnect

Update docs and comments (MessageQueue, forceReconnect)

---

src/main/java/io/nats/client/impl/NatsConnection.java
src/test/java/io/nats/client/impl/ConnectionListenerTests.java

Remove duplicate reconnect event

---

src/main/java/io/nats/client/Connection.java
src/main/java/io/nats/client/ForceReconnectOptions.java
src/main/java/io/nats/client/Options.java
src/main/java/io/nats/client/impl/NatsConnection.java
src/main/java/io/nats/client/impl/SocketDataPortWithWriteTimeout.java
src/test/java/io/nats/client/impl/ForceReconnectQueueCheckDataPort.java
src/test/java/io/nats/client/impl/ReconnectTests.java

Added the ability to customize how `forceReconnect` is called.

Augmented force reconnect

---

src/main/java/io/nats/client/KeyValue.java
src/main/java/io/nats/client/api/OrderedConsumerConfiguration.java
src/main/java/io/nats/client/impl/NatsFeatureBase.java
src/main/java/io/nats/client/impl/NatsKeyValue.java
src/main/java/io/nats/client/support/NatsJetStreamConstants.java
src/test/java/io/nats/client/impl/KeyValueTests.java

Addresses https://github.com/nats-io/nats.java/issues/1163

Add filtering to KV keys methods

---

src/main/java/io/nats/client/Options.java
src/test/java/io/nats/client/OptionsTests.java

Address Issue https://github.com/nats-io/nats.java/issues/1182

Handle duration string when accepting duration properties

---

src/main/java/io/nats/client/JetStream.java

Jetstream Usage

---

src/main/java/io/nats/client/impl/NatsConnection.java
src/main/java/io/nats/client/impl/NatsJetStream.java
src/main/java/io/nats/client/impl/NatsJetStreamImpl.java
src/main/java/io/nats/client/impl/NatsJetStreamMessage.java
src/main/java/io/nats/client/impl/NatsJetStreamMetaData.java
src/main/java/io/nats/client/impl/NatsPublishableMessage.java
src/test/java/io/nats/client/impl/NatsJetStreamMetaDataTests.java
src/test/java/io/nats/client/impl/ReconnectTests.java

Trying to address super high volume consuming.

Minor refactoring and regression test change.

---

README.md
src/main/java/io/nats/client/support/ApiConstants.java
src/main/java/io/nats/service/Service.java
src/main/java/io/nats/service/ServiceBuilder.java
src/test/java/io/nats/service/ServiceTests.java

Remove Schema related leftovers

---

src/main/java/io/nats/client/impl/NatsKeyValue.java
src/main/java/io/nats/client/impl/NatsKeyValueWatchSubscription.java
src/test/java/io/nats/client/impl/KeyValueTests.java

KV Minor Changes

---

src/main/java/io/nats/client/Nats.java
src/main/java/io/nats/client/Options.java

Signed-off-by: Tomasz Pietrek <tomasz@nats.io>

Remove the experimental mentions

---

src/main/java/io/nats/client/Options.java
src/main/java/io/nats/client/impl/NatsConnection.java
src/main/java/io/nats/client/impl/SocketDataPort.java
src/test/java/io/nats/client/ConnectTests.java
src/test/java/io/nats/client/OptionsTests.java

Implement Fast fallback algorithm in SocketDataPort

---

src/main/java/io/nats/client/ForceReconnectOptions.java
src/main/java/io/nats/client/impl/NatsConnection.java
src/test/java/io/nats/client/api/ServerInfoTests.java
src/test/java/io/nats/client/impl/ReconnectTests.java
src/test/java/io/nats/client/utils/TestBase.java

Review for Issues #1361 and #1362
Added comments to show where places were checked, updated a unit test, etc.

Review for Issues #1361 and #1362

---

src/main/java/io/nats/client/impl/NatsConsumer.java

* StreamInfo allow_msg_counter
* direct message api no_hdrs

(2.12) Message Counter support
